import type { Region } from "./types";

/** Referans atlas bölgeleri — Supabase kayıt katmanı gelene kadar sabit örnek set. Konumlar % (sol-üst). */
export const ATLAS_REGIONS: Region[] = [
  {
    id: "mesane-left-taban",
    organ: "Mesane",
    footSide: "left",
    view: "taban",
    x: 38,
    y: 68,
    width: 16,
    height: 11,
    shapeType: "oval",
    color: "rgba(167, 139, 250, 0.52)",
  },
  {
    id: "mesane-right-taban",
    organ: "Mesane",
    footSide: "right",
    view: "taban",
    x: 46,
    y: 70,
    width: 15,
    height: 10,
    shapeType: "oval",
    color: "rgba(167, 139, 250, 0.52)",
  },
  {
    id: "bobrek-left-taban",
    organ: "Böbrek",
    footSide: "left",
    view: "taban",
    x: 22,
    y: 42,
    width: 18,
    height: 14,
    shapeType: "oval",
    color: "rgba(129, 140, 248, 0.5)",
  },
  {
    id: "bobrek-right-taban",
    organ: "Böbrek",
    footSide: "right",
    view: "taban",
    x: 58,
    y: 44,
    width: 17,
    height: 13,
    shapeType: "oval",
    color: "rgba(129, 140, 248, 0.5)",
  },
  {
    id: "bobrek-left-yan",
    organ: "Böbrek",
    footSide: "left",
    view: "yan",
    x: 12,
    y: 38,
    width: 12,
    height: 22,
    shapeType: "oval",
    color: "rgba(99, 102, 241, 0.45)",
  },
  {
    id: "karaciger-left-taban",
    organ: "Karaciğer",
    footSide: "left",
    view: "taban",
    x: 52,
    y: 28,
    width: 20,
    height: 12,
    shapeType: "oval",
    color: "rgba(251, 191, 36, 0.48)",
  },
  {
    id: "karaciger-right-taban",
    organ: "Karaciğer",
    footSide: "right",
    view: "taban",
    x: 30,
    y: 30,
    width: 19,
    height: 11,
    shapeType: "oval",
    color: "rgba(251, 191, 36, 0.48)",
  },
  {
    id: "mide-left-taban",
    organ: "Mide",
    footSide: "left",
    view: "taban",
    x: 40,
    y: 38,
    width: 17,
    height: 12,
    shapeType: "oval",
    color: "rgba(52, 211, 153, 0.48)",
  },
  {
    id: "mide-right-taban",
    organ: "Mide",
    footSide: "right",
    view: "taban",
    x: 42,
    y: 40,
    width: 16,
    height: 11,
    shapeType: "oval",
    color: "rgba(52, 211, 153, 0.48)",
  },
  {
    id: "mide-left-yan",
    organ: "Mide",
    footSide: "left",
    view: "yan",
    x: 28,
    y: 32,
    width: 14,
    height: 18,
    shapeType: "oval",
    color: "rgba(16, 185, 129, 0.42)",
  },
];
