// Demo fixture verisi — yalnızca is_demo_account=true hesabında devreye girer. DB'ye yazılmaz.

import type { AromatherapyOil, OilListRow } from "@/lib/aromaterapi/aromatherapyData";

export const DEMO_AROMA_PREFIX = "demo-aromatik-";

export function isDemoFixtureOil(id: string): boolean {
  return id.startsWith(DEMO_AROMA_PREFIX);
}

// ─── Fixture Yağlar ───────────────────────────────────────────────────────────

export const DEMO_SEED_OILS_FULL: AromatherapyOil[] = [
  {
    id: "demo-aromatik-lavanta",
    tenant_id: null,
    name: "Lavanta",
    latin_name: "Lavandula angustifolia",
    english_name: "Lavender",
    oil_type: "essential",
    category: "Çiçek",
    extraction_method: "Buhar damıtma",
    plant_part: "Çiçek ve yaprak",
    origin: "Fransa, Türkiye",
    shelf_life: "3-5 yıl",
    aroma_profile: "Çiçeksi, tatlı, hafif odunsu ve balsamic alt notalar; narin ve sakinleştirici",
    aroma_note: "Orta nota",
    color: "Soluk sarı veya renksiz",
    consistency: "İnce, sıvı",
    is_photosensitive: false,
    main_components: "Linalool (%25-46), Linalyl asetat (%25-46), β-Osimen, Teri-4-ol",
    therapeutic_properties: ["antiseptik", "anti-inflamatuar", "analjezik", "sedatif", "antimikrobiyal"],
    emotional_benefits: "Stresi ve kaygıyı giderir; sinir sistemini dengeler, zihinsel yorgunluğu azaltır, iç huzuru destekler.",
    spiritual_benefits: "Meditatif ortam oluşturur; enerji alanını arındırır, şefkat ve sezgiyi açar.",
    physical_benefits: "Uyku kalitesini artırır, baş ağrısını hafiflatar, kasları gevşetir; küçük yanık ve tahrişlere yardımcı olur.",
    skin_benefits: "Cilt yenilenmesini hızlandırır, sivilce izlerini azaltır, skar dokusunu hafifletir.",
    benefits: "Çok yönlü referans yağ; rahatlatıcı, iyileştirici ve dengeleyici etkileriyle aromaterapi temel kitliğinin vazgeçilmezi.",
    diffuser_usage: "Difüzöre 3-5 damla. Uyku öncesi yatak odasında seyreltilmiş oda spreyi olarak uygulanabilir.",
    massage_usage: "Taşıyıcı yağda %2-3 seyreltip masajda kullanın; boyun, omuz ve bel gerginliği için idealdir.",
    usage_methods: "İnhalasyon, aromatik banyo, masaj, kompres, koku yayıcı, oda spreyi.",
    dilution_ratio: "%1-3",
    blends_well_with: ["bergamot", "sandal ağacı", "geranium", "sedirağacı", "neroli"],
    target_systems: ["sinir sistemi", "deri sistemi", "bağışıklık sistemi"],
    chakra_connection: "Taç Çakrası, Kalp Çakrası",
    element_connection: "Hava",
    safety_notes: "Genel olarak güvenlidir. Hassas bireylerde önce küçük bir bölgede test edin. Göz ile temastan kaçının.",
    contraindications: "Gebeliğin ilk trimesterinde ihtiyatlı kullanın. Bebeklerde direkt cilt temasından kaçının.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-01T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-bergamot",
    tenant_id: null,
    name: "Bergamot",
    latin_name: "Citrus bergamia",
    english_name: "Bergamot",
    oil_type: "essential",
    category: "Narenciye",
    extraction_method: "Soğuk pres",
    plant_part: "Meyve kabuğu",
    origin: "İtalya (Kalabria), Fildişi Sahili",
    shelf_life: "2-3 yıl",
    aroma_profile: "Ferah, narenciye, hafif çiçeksi ve baharatlı; tatlı-ekşi dengeli üst nota",
    aroma_note: "Üst nota",
    color: "Soluk yeşil-sarı",
    consistency: "İnce, sıvı",
    is_photosensitive: true,
    main_components: "Linalyl asetat (%30-45), Linalool (%10-22), γ-Terpinen, Bergapten (FCF versiyonda giderilmiş)",
    therapeutic_properties: ["antidepresif", "antiseptik", "anksiyolitik", "antibakteriyel", "antispazmodik"],
    emotional_benefits: "Ruh halini yükseltir; üzüntü, kaygı ve depresif duyguları hafifletir. Özgüven ve neşeyi destekler.",
    spiritual_benefits: "İçsel ışığı ve pozitif enerjiyi artırır; zihinsel berraklık sağlar.",
    physical_benefits: "Sindirim sistemini rahatlatır, iştah dengesini destekler, ağız bakımı için etkilidir.",
    skin_benefits: "Yağlı ve karma ciltleri dengeler; sivilce ve cilt enfeksiyonlarını azaltmaya yardımcı olur.",
    benefits: "Antidepresif ve dengeleyici etkisiyle akıl sağlığı protokollerinde sıkça tercih edilen bir narenciye yağı.",
    diffuser_usage: "Sabah saatlerinde difüzöre 3-4 damla; çalışma ortamında odaklanmayı artırır.",
    massage_usage: "Taşıyıcı yağda %1-2 seyreltip karın masajında veya lenf bölgelerinde kullanın.",
    usage_methods: "Difüzyon, masaj, banyo (seyreltilmiş), oda spreyi.",
    dilution_ratio: "%1-2 (fotosensitif)",
    blends_well_with: ["lavanta", "ylang ylang", "sandalwood", "frankincense", "geranium"],
    target_systems: ["sinir sistemi", "sindirim sistemi", "deri sistemi"],
    chakra_connection: "Solar Pleksus Çakrası, Kalp Çakrası",
    element_connection: "Hava, Ateş",
    safety_notes: "FOTOSENSİTİF: Uygulamadan sonra 12-24 saat güneşe çıkmaktan kaçının. FCF (bergapten-free) versiyonu daha güvenlidir.",
    contraindications: "Güneş ışığına maruz kalacak bölgelere doğrudan uygulamayın. Gebelikte dikkatli kullanın.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-02T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-biberiye",
    tenant_id: null,
    name: "Biberiye",
    latin_name: "Rosmarinus officinalis",
    english_name: "Rosemary",
    oil_type: "essential",
    category: "Otsu Bitki",
    extraction_method: "Buhar damıtma",
    plant_part: "Yaprak ve çiçek",
    origin: "İspanya, Fransa, Türkiye",
    shelf_life: "3-4 yıl",
    aroma_profile: "Sert, aromatik, kamphorlu ve nane benzeri; temiz ve keskin koku",
    aroma_note: "Üst-Orta nota",
    color: "Renksiz veya soluk sarı",
    consistency: "İnce, sıvı",
    is_photosensitive: false,
    main_components: "1,8-Sineol (%35-55), α-Pinene (%15-25), Kamfor (%5-15), Kamfen",
    therapeutic_properties: ["uyarıcı", "analeptik", "analjesik", "antibakteriyel", "antioksidan"],
    emotional_benefits: "Zihni keskinleştirir, hafızayı güçlendirir, yorgunluk ve zihinsel tükenmişliği giderir.",
    spiritual_benefits: "Enerji akışını canlandırır; yaratıcılığı ve netliği destekler, geçmişi bırakmaya yardımcı olur.",
    physical_benefits: "Baş ağrısını ve migreni hafifletir; saç dökülmesini azaltmaya yardımcı olur, kas ağrılarını giderir.",
    skin_benefits: "Saç derisini uyarır, kepek ve saç dökülmesine karşı etkilidir.",
    benefits: "Odaklanma, enerji ve fiziksel performans için vazgeçilmez bir yağ; kadim halk tıbbında geniş kullanım alanı.",
    diffuser_usage: "Çalışma ortamında konsantrasyonu artırmak için 3-4 damla; sabah ritüeli için ideal.",
    massage_usage: "Spor öncesi %2-3 seyreltilmiş karışımla kas masajı; biberiye + kırmızı biber + jojoba kombinasyonu.",
    usage_methods: "Difüzyon, masaj, saç bakımı (seyreltilmiş), inhalasyon.",
    dilution_ratio: "%2-3",
    blends_well_with: ["lavanta", "nane", "ökaliptüs", "limon", "biberiye"],
    target_systems: ["sinir sistemi", "kas-iskelet sistemi", "deri sistemi (saç)"],
    chakra_connection: "Baş Çakrası",
    element_connection: "Ateş, Hava",
    safety_notes: "Yüksek tansiyon ve epilepsi hastalarında kullanmayın. Çocuklarda ve hamile kadınlarda dikkatli olun.",
    contraindications: "Epilepsi, hipertansiyon, gebelik. 6 yaş altı çocuklarda kullanmayın.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-03T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-okaliptus",
    tenant_id: null,
    name: "Ökaliptüs",
    latin_name: "Eucalyptus globulus",
    english_name: "Eucalyptus",
    oil_type: "essential",
    category: "Ağaç",
    extraction_method: "Buhar damıtma",
    plant_part: "Yaprak ve dal",
    origin: "Avustralya, Çin, İspanya",
    shelf_life: "4-5 yıl",
    aroma_profile: "Güçlü, keskin, kamphorlu ve ferahlatıcı; neredeyse mentol etkisi veren temiz koku",
    aroma_note: "Üst nota",
    color: "Renksiz",
    consistency: "İnce, sıvı",
    is_photosensitive: false,
    main_components: "1,8-Sineol (Ökaliptol) (%60-85), α-Pinene, Limonene, p-Simen",
    therapeutic_properties: ["ekspektoran", "antiviral", "antibakteriyel", "dekonjestan", "anti-inflamatuar"],
    emotional_benefits: "Akıl karmaşıklığını giderir; konsantrasyonu artırır, enerji verir ve tazelik hissi yaratır.",
    spiritual_benefits: "Fiziksel ve enerjetik blokajları kaldırır; nefes çalışmalarında yolu açar.",
    physical_benefits: "Üst solunum yolu enfeksiyonlarını hafifletir, sinüs tıkanıklığını giderir, bronşiti destekler.",
    skin_benefits: "Antiseptik özelliği sayesinde küçük yaraların iyileşmesini destekler.",
    benefits: "Solunum sağlığı için birincil tercih; soğuk algınlığı ve grip mevsiminin vazgeçilmez yağı.",
    diffuser_usage: "Solunum desteği için difüzöre 4-6 damla; buhar inhalasyonu için sıcak suya 2-3 damla.",
    massage_usage: "Göğüs masajı için taşıyıcı yağda %1-2 seyreltip uygulayın.",
    usage_methods: "Difüzyon, buhar inhalasyonu, göğüs masajı, oda dezenfeksiyonu.",
    dilution_ratio: "%1-2",
    blends_well_with: ["nane", "limon", "lavanta", "biberiye", "çay ağacı"],
    target_systems: ["solunum sistemi", "bağışıklık sistemi"],
    chakra_connection: "Boğaz Çakrası",
    element_connection: "Hava",
    safety_notes: "Çocuklarda yüz bölgesine uygulamayın (özellikle burun altı). Seyreltmeden kullanmayın.",
    contraindications: "2 yaş altı çocuklarda kullanmayın. Astım hastalarında dikkatli olun.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-04T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-frankincense",
    tenant_id: null,
    name: "Frankincense (Günlük)",
    latin_name: "Boswellia carterii",
    english_name: "Frankincense",
    oil_type: "essential",
    category: "Reçine",
    extraction_method: "Buhar damıtma",
    plant_part: "Reçine",
    origin: "Somali, Etiyopya, Umman",
    shelf_life: "4-6 yıl",
    aroma_profile: "Derin, balsamic, tatlı-reçineli; duman ve odun alt notalar; zamanla açılan kadim koku",
    aroma_note: "Alt-Orta nota",
    color: "Soluk sarı-yeşil",
    consistency: "İnce ile orta arası",
    is_photosensitive: false,
    main_components: "α-Pinene (%35-55), Limonene (%10-15), α-Terpinen, İnsenol",
    therapeutic_properties: ["immünomodülatör", "anti-inflamatuar", "antiseptik", "astrenjan", "sedatif"],
    emotional_benefits: "Derin sakinliği teşvik eder; korku ve endişeyi azaltır, ruhsal bağlantıyı güçlendirir.",
    spiritual_benefits: "Kadim zamanlarda ritüellerde kullanılan bu yağ; meditasyon derinliğini artırır ve spiritüel uyanışı destekler.",
    physical_benefits: "Bağışıklık sistemini güçlendirir; kronik iltihaplanmayı azaltır, ağrı yönetimine katkı sağlar.",
    skin_benefits: "Yaşlanma karşıtı etkisi ile kırışıklıkları azaltır, cildi sıkılaştırır ve parlaklaştırır.",
    benefits: "Ruhsal ve bedensel denge için en bütünleşik yağlardan biri; tüm çakra sistemiyle rezonans kurar.",
    diffuser_usage: "Meditasyon seansı öncesi difüzöre 3-4 damla; lavanta ile kombinasyon ideal.",
    massage_usage: "Taşıyıcı yağda %1-2 seyreltip yüz ve boyun masajında kullanın.",
    usage_methods: "Difüzyon, meditasyon, yüz bakımı, inhalasyon.",
    dilution_ratio: "%1-2",
    blends_well_with: ["lavanta", "bergamot", "mür", "sandalwood", "gül"],
    target_systems: ["bağışıklık sistemi", "sinir sistemi", "deri sistemi"],
    chakra_connection: "Taç Çakrası, Üçüncü Göz Çakrası",
    element_connection: "Eter",
    safety_notes: "Genel olarak güvenlidir. Gebelikte ihtiyatlı kullanın. Seyreltilmeden cilde uygulamayın.",
    contraindications: "Antikoagülan ilaç kullananlar dikkatli kullanmalıdır.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-05T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-jojoba",
    tenant_id: null,
    name: "Jojoba",
    latin_name: "Simmondsia chinensis",
    english_name: "Jojoba",
    oil_type: "carrier",
    category: "Sabit Yağ",
    extraction_method: "Soğuk pres",
    plant_part: "Tohum",
    origin: "ABD (Arizona), Meksika, Arjantin",
    shelf_life: "5+ yıl (çok kararlı)",
    aroma_profile: "Neredeyse kokusuz; hafif fındıksı, nötr yapı",
    aroma_note: "Tabanı",
    color: "Altın sarısı (soğuk pres), renksiz (rafine)",
    consistency: "Orta, sıvı kristal (teknik olarak mum)",
    is_photosensitive: false,
    main_components: "Wax esterler (%97+): eikosenoik asit, erüsik asit, dokosenol; E vitamini",
    therapeutic_properties: ["nemlendirici", "sebo düzenleyici", "antioksidan", "anti-inflamatuar"],
    emotional_benefits: "Derin cilt bakımı ritüeli aracılığıyla beden-zihin bütünleşmesini destekler.",
    spiritual_benefits: "Öz-sevgi ve beden şefkati pratiğinde taşıyıcı yağ olarak kullanılır.",
    physical_benefits: "İnsan deri sebomu ile benzer yapısı sayesinde her cilt tipine uyar; kuruluğu giderir.",
    skin_benefits: "Gözenek tıkamaz, yağlı ciltler dahil her cilt için idealdir. Akne sklıkla azalır.",
    benefits: "Aromaterapi taşıyıcı yağlarının altın standardı; kararlı yapısı ve çok yönlü kullanımıyla öne çıkar.",
    diffuser_usage: "Uçucu yağlar için taşıyıcı; seyreltme yağı olarak kullanılır.",
    massage_usage: "Masaj bazı olarak direkt kullanılabilir. Uçucu yağlarla karıştırın.",
    usage_methods: "Masaj tabanı, seyreltme yağı, cilt ve saç bakımı.",
    dilution_ratio: "%100 güvenli, taşıyıcı",
    blends_well_with: ["lavanta", "biberiye", "jojoba", "argan"],
    target_systems: ["deri sistemi"],
    chakra_connection: "Kök Çakrası",
    element_connection: "Toprak",
    safety_notes: "Çok nadiren alerjik reaksiyon. Genel olarak en güvenli taşıyıcı yağlardan biridir.",
    contraindications: "Fındık alerjisi olanlarda (çok nadir) reaksiyon görülebilir.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-06T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-argan",
    tenant_id: null,
    name: "Argan",
    latin_name: "Argania spinosa",
    english_name: "Argan",
    oil_type: "carrier",
    category: "Sabit Yağ",
    extraction_method: "Soğuk pres",
    plant_part: "Çekirdek",
    origin: "Fas (Güneybatı)",
    shelf_life: "2-3 yıl",
    aroma_profile: "Hafif fındıksı ve nötr; kozmetik kalitede neredeyse kokusuz",
    aroma_note: "Tabanı",
    color: "Altın sarısı",
    consistency: "Hafif-orta, kuru his bırakan",
    is_photosensitive: false,
    main_components: "Oleik asit (%45-50), Linoleik asit (%29-36), E vitamini (Tokoferoller), Fenolik bileşikler",
    therapeutic_properties: ["antioksidan", "nemlendirici", "besleyici", "elastikiyet artırıcı"],
    emotional_benefits: "Lüks cilt bakımı ritüeli aracılığıyla öz-değer ve öz-bakım duygusunu pekiştirir.",
    spiritual_benefits: "Fas'ın bereket yağı olarak bilinen argan; bolluk ve şükran enerjisi taşır.",
    physical_benefits: "Eklem ve kas ağrılarına karşı sıkça kullanılır; anti-inflamatuar bileşenleri bunu destekler.",
    skin_benefits: "Cildi derinlemesine nemlendirir; kırışıklıkları, skar dokusunu ve tutarsız tonu iyileştirir.",
    benefits: "Dünya genelinde 'Fas'ın sıvı altını' olarak bilinen bu yağ, hem cilt hem saç bakımında benzersiz sonuçlar verir.",
    diffuser_usage: "Taşıyıcı yağ; uçucu yağlarla seyreltme yağı olarak kullanılır.",
    massage_usage: "Yüz ve saç masajında direkt ya da uçucu yağlarla karıştırarak kullanın.",
    usage_methods: "Cilt bakımı, saç bakımı, seyreltme yağı, masaj.",
    dilution_ratio: "%100 güvenli, taşıyıcı",
    blends_well_with: ["gül", "neroli", "frankincense", "lavanta"],
    target_systems: ["deri sistemi"],
    chakra_connection: "Kök Çakrası, Taç Çakrası",
    element_connection: "Toprak",
    safety_notes: "Çok nadiren tahriş. Argan tozu alerjisi olanlar dikkatli kullanmalıdır.",
    contraindications: "Fındık alerjisinde dikkatli olun.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-07T10:00:00.000Z",
    updated_at: null,
  },
  {
    id: "demo-aromatik-kantaron",
    tenant_id: null,
    name: "Kantaron (Sarı Kantaron)",
    latin_name: "Hypericum perforatum",
    english_name: "St. John's Wort",
    oil_type: "maceration",
    category: "Maserasyon",
    extraction_method: "Soğuk maserasyon (ayçiçeği veya zeytinyağında)",
    plant_part: "Çiçek ve tomurcuk",
    origin: "Türkiye, Avrupa",
    shelf_life: "1-2 yıl",
    aroma_profile: "Otsu, hafif reçineli ve tatlı; sarı çiçeklerin narin kokusu",
    aroma_note: "Tabanı",
    color: "Kırmızı-kızıl (hypericin pigmenti)",
    consistency: "Orta, hafif ağır",
    is_photosensitive: true,
    main_components: "Hypericin, Hyperforin, Flavonoidler (Quercetin, Kaempferol), Tanen",
    therapeutic_properties: ["anti-nöraljik", "anti-inflamatuar", "yara iyileştirici", "antiseptik"],
    emotional_benefits: "Geleneksel olarak hafif depresif duyguları dengelemede yardımcı olduğu bilinir.",
    spiritual_benefits: "Güneş ile ilişkilendirilen bu bitki; ışık ve umut enerjisi taşır.",
    physical_benefits: "Sinir ağrılarını (siyatik, nevralji) hafifletir; yaraların ve yanıkların iyileşmesini hızlandırır.",
    skin_benefits: "Güneş yanığına, küçük yaralara ve cilt tahrişlerine karşı geleneksel çözüm.",
    benefits: "Yüzyıllardır kullanılan doğal iyileştirici; sinir sistemi ve deri için bütünleşik etki.",
    diffuser_usage: "Maserasyon yağı olarak difüzyon için kullanılmaz; taşıyıcı/terapötik bazda kullanılır.",
    massage_usage: "Siyatik ve nevralji masajında direkt uygulanabilir; uçucu yağlarla karıştırın.",
    usage_methods: "Lokal masaj, kompres, cilt bakımı.",
    dilution_ratio: "%100 uygulanabilir (maserasyon yağı)",
    blends_well_with: ["lavanta", "biberiye", "papatya"],
    target_systems: ["sinir sistemi", "deri sistemi", "kas-iskelet sistemi"],
    chakra_connection: "Solar Pleksus Çakrası",
    element_connection: "Ateş",
    safety_notes: "FOTOSENSİTİF: Uygulamadan sonra güneşe çıkmayın. Antidepresan ve antikoagülan ilaçlarla etkileşim.",
    contraindications: "SSRI/antidepresan kullananlar, gebelik ve emzirme döneminde kullanmayın. Güneşe maruz kalmadan önce yıkayın.",
    images: [],
    notes: "",
    source: "Demo referans verisi",
    is_active: true,
    created_at: "2025-01-08T10:00:00.000Z",
    updated_at: null,
  },
];

// OilListRow formatında (subset) — liste sayfaları için
export const DEMO_SEED_OILS: OilListRow[] = DEMO_SEED_OILS_FULL as OilListRow[];

// ─── Yardımcılar ──────────────────────────────────────────────────────────────

export function getDemoOilDetail(id: string): AromatherapyOil | null {
  return DEMO_SEED_OILS_FULL.find((o) => o.id === id) ?? null;
}

export function getDemoOilStats() {
  const total      = DEMO_SEED_OILS_FULL.length;
  const essential  = DEMO_SEED_OILS_FULL.filter((o) => o.oil_type === "essential").length;
  const carrier    = DEMO_SEED_OILS_FULL.filter((o) => o.oil_type === "carrier").length;
  const maceration = DEMO_SEED_OILS_FULL.filter((o) => o.oil_type === "maceration").length;
  const other      = total - essential - carrier - maceration;
  return { total, essential, carrier, maceration, other };
}

// Aromaterapi için localStorage kullanılmıyor — clearDemoAromaterapi no-op
export function clearDemoAromaterapi(): void {
  // Gelecekte favoriler/karışımlar eklendikçe bu fonksiyon güncellenir
}
