export const HUMAN_DESIGN_TYPES = [
  { code: "generator",             label: "Generator" },
  { code: "manifesting_generator", label: "Manifesting Generator" },
  { code: "projector",             label: "Projector" },
  { code: "manifestor",            label: "Manifestor" },
  { code: "reflector",             label: "Reflector" },
] as const;

export const HUMAN_DESIGN_AUTHORITIES = [
  { code: "sacral",               label: "Sacral Otorite" },
  { code: "emotional",            label: "Emotional / Solar Plexus" },
  { code: "splenic",              label: "Splenic (Dalak)" },
  { code: "ego_heart",            label: "Ego / Heart" },
  { code: "self_projected",       label: "Self-Projected" },
  { code: "mental_environmental", label: "Mental / Environmental" },
  { code: "lunar",                label: "Lunar (Ay)" },
] as const;

export const HUMAN_DESIGN_PROFILES = [
  { code: "1_3", label: "1/3 — Araştırmacı / Şehit" },
  { code: "1_4", label: "1/4 — Araştırmacı / Fırsatçı" },
  { code: "2_4", label: "2/4 — Münzevi / Fırsatçı" },
  { code: "2_5", label: "2/5 — Münzevi / Sapkın" },
  { code: "3_5", label: "3/5 — Şehit / Sapkın" },
  { code: "3_6", label: "3/6 — Şehit / Rol Model" },
  { code: "4_6", label: "4/6 — Fırsatçı / Rol Model" },
  { code: "4_1", label: "4/1 — Fırsatçı / Araştırmacı" },
  { code: "5_1", label: "5/1 — Sapkın / Araştırmacı" },
  { code: "5_2", label: "5/2 — Sapkın / Münzevi" },
  { code: "6_2", label: "6/2 — Rol Model / Münzevi" },
  { code: "6_3", label: "6/3 — Rol Model / Şehit" },
] as const;

export const HUMAN_DESIGN_DEFINITIONS = [
  { code: "single",          label: "Tekli Tanım" },
  { code: "split",           label: "İkili Tanım (Split)" },
  { code: "triple_split",    label: "Üçlü Tanım (Triple Split)" },
  { code: "quadruple_split", label: "Dörtlü Tanım (Quadruple Split)" },
] as const;

export const HUMAN_DESIGN_CENTERS = [
  { code: "head",        label: "Head / Baş Merkezi" },
  { code: "ajna",        label: "Ajna Merkezi" },
  { code: "throat",      label: "Throat / Boğaz Merkezi" },
  { code: "g_identity",  label: "G / Kimlik Merkezi" },
  { code: "heart_ego",   label: "Heart / Ego Merkezi" },
  { code: "solar_plexus",label: "Solar Plexus Merkezi" },
  { code: "sacral",      label: "Sacral Merkezi" },
  { code: "spleen",      label: "Spleen / Dalak Merkezi" },
  { code: "root",        label: "Root / Kök Merkezi" },
] as const;

export const HUMAN_DESIGN_GATES: { code: number; label: string }[] = [
  { code:  1, label:  "1 — Kendini ifade kapısı" },
  { code:  2, label:  "2 — Yön kapısı" },
  { code:  3, label:  "3 — Düzen sağlama kapısı" },
  { code:  4, label:  "4 — Yanıtlar kapısı" },
  { code:  5, label:  "5 — Kalıplar-bekleyiş kapısı" },
  { code:  6, label:  "6 — Çatışma kapısı" },
  { code:  7, label:  "7 — Liderlik kapısı" },
  { code:  8, label:  "8 — Katkı kapısı" },
  { code:  9, label:  "9 — Odaklanma kapısı" },
  { code: 10, label: "10 — Benlik sevgisi" },
  { code: 11, label: "11 — Fikirler kapısı" },
  { code: 12, label: "12 — İhtiyat kapısı" },
  { code: 13, label: "13 — Dinleyici kapısı" },
  { code: 14, label: "14 — Güç becerileri kapısı" },
  { code: 15, label: "15 — Aşırı uçlar kapısı" },
  { code: 16, label: "16 — Beceriler kapısı" },
  { code: 17, label: "17 — Kanılar kapısı" },
  { code: 18, label: "18 — Düzeltme kapısı" },
  { code: 19, label: "19 — İstemek kapısı" },
  { code: 20, label: "20 — Başkalaşım kapısı" },
  { code: 21, label: "21 — Haznedar kapısı" },
  { code: 22, label: "22 — Zarafet kapısı" },
  { code: 23, label: "23 — Özümseme kapısı" },
  { code: 24, label: "24 — Rasyonelleştirme kapısı" },
  { code: 25, label: "25 — Masumiyet kapısı" },
  { code: 26, label: "26 — Düzenbaz kapısı" },
  { code: 27, label: "27 — Sorumluluk kapısı" },
  { code: 28, label: "28 — Mücadele kapısı" },
  { code: 29, label: "29 — Sebat kapısı" },
  { code: 30, label: "30 — Arzu kapısı" },
  { code: 31, label: "31 — Demokrasi kapısı" },
  { code: 32, label: "32 — Devamlılık kapısı" },
  { code: 33, label: "33 — Mahremiyet kapısı" },
  { code: 34, label: "34 — Güç kapısı" },
  { code: 35, label: "35 — Değişim kapısı" },
  { code: 36, label: "36 — Kriz kapısı" },
  { code: 37, label: "37 — Dostluk kapısı" },
  { code: 38, label: "38 — Savaşçı kapısı" },
  { code: 39, label: "39 — Kışkırtma kapısı" },
  { code: 40, label: "40 — Yalnızlık kapısı" },
  { code: 41, label: "41 — Azalma kapısı" },
  { code: 42, label: "42 — Bitirme kapısı" },
  { code: 43, label: "43 — İç görü kapısı" },
  { code: 44, label: "44 — Karşılayıcı-enerji kapısı" },
  { code: 45, label: "45 — Kral ya da kraliçe kapısı" },
  { code: 46, label: "46 — Beden sevgisi" },
  { code: 47, label: "47 — Kavrayış kapısı" },
  { code: 48, label: "48 — Derinlik kapısı" },
  { code: 49, label: "49 — Devrim kapısı" },
  { code: 50, label: "50 — Değerler kapısı" },
  { code: 51, label: "51 — Şok kapısı" },
  { code: 52, label: "52 — Hareketsizlik kapısı" },
  { code: 53, label: "53 — İlerleme kapısı" },
  { code: 54, label: "54 — Dürtü kapısı" },
  { code: 55, label: "55 — Ruh kapısı" },
  { code: 56, label: "56 — Öykücü kapısı" },
  { code: 57, label: "57 — Sezgi kapısı" },
  { code: 58, label: "58 — Sevinç kapısı" },
  { code: 59, label: "59 — Cinsellik kapısı" },
  { code: 60, label: "60 — Kabullenme kapısı" },
  { code: 61, label: "61 — Gizem kapısı" },
  { code: 62, label: "62 — Ayrıntılar kapısı" },
  { code: 63, label: "63 — Kuşku-şüphe kapısı" },
  { code: 64, label: "64 — Şüphe kapısı" },
];

export const HUMAN_DESIGN_CHANNELS = [
  { code: "1-8",   label: "1-8 İlham Kanalı" },
  { code: "2-14",  label: "2-14 Ritim Kanalı" },
  { code: "3-60",  label: "3-60 Mutasyon Kanalı" },
  { code: "4-63",  label: "4-63 Mantık Kanalı" },
  { code: "5-15",  label: "5-15 Ritim Kanalı" },
  { code: "6-59",  label: "6-59 Yakınlık Kanalı" },
  { code: "7-31",  label: "7-31 Alfa Kanalı" },
  { code: "9-52",  label: "9-52 Konsantrasyon Kanalı" },
  { code: "10-20", label: "10-20 Uyanış Kanalı" },
  { code: "10-34", label: "10-34 Keşif Kanalı" },
  { code: "10-57", label: "10-57 Mükemmel Form Kanalı" },
  { code: "11-56", label: "11-56 Merak Kanalı" },
  { code: "12-22", label: "12-22 Açıklık Kanalı" },
  { code: "13-33", label: "13-33 Tanıklık Kanalı" },
  { code: "16-48", label: "16-48 Yetenek Kanalı" },
  { code: "17-62", label: "17-62 Kabul Kanalı" },
  { code: "18-58", label: "18-58 Yargı Kanalı" },
  { code: "19-49", label: "19-49 Sentez Kanalı" },
  { code: "20-34", label: "20-34 Karizma Kanalı" },
  { code: "20-57", label: "20-57 Beyin Dalgası Kanalı" },
  { code: "21-45", label: "21-45 Para Kanalı" },
  { code: "23-43", label: "23-43 Yapılandırma Kanalı" },
  { code: "24-61", label: "24-61 Farkındalık Kanalı" },
  { code: "25-51", label: "25-51 Başlatma Kanalı" },
  { code: "26-44", label: "26-44 Teslimiyet Kanalı" },
  { code: "27-50", label: "27-50 Koruma Kanalı" },
  { code: "28-38", label: "28-38 Mücadele Kanalı" },
  { code: "29-46", label: "29-46 Keşif Kanalı" },
  { code: "30-41", label: "30-41 Tanıma Kanalı" },
  { code: "32-54", label: "32-54 Dönüşüm Kanalı" },
  { code: "34-57", label: "34-57 Güç Kanalı" },
  { code: "35-36", label: "35-36 Geçicilik Kanalı" },
  { code: "37-40", label: "37-40 Topluluk Kanalı" },
  { code: "39-55", label: "39-55 Duygusallık Kanalı" },
  { code: "42-53", label: "42-53 Olgunlaşma Kanalı" },
  { code: "47-64", label: "47-64 Soyutlama Kanalı" },
] as const;

export const HD_KNOWLEDGE_CATEGORIES = [
  "Tipler",
  "Otoriteler",
  "Profiller",
  "Tanımlar",
  "Merkezler",
  "Kanallar",
  "Kapılar",
  "Stratejiler",
  "Genel Notlar",
] as const;

export type HdKnowledgeCategory = (typeof HD_KNOWLEDGE_CATEGORIES)[number];

export const HD_KNOWLEDGE_CATEGORY_PREFIX: Record<HdKnowledgeCategory, string> = {
  Tipler:          "tip",
  Otoriteler:      "otorite",
  Profiller:       "profil",
  Tanımlar:        "tanim",
  Merkezler:       "merkez",
  Kanallar:        "kanal",
  Kapılar:         "kapi",
  Stratejiler:     "strateji",
  "Genel Notlar":  "not",
};
