export type GateTechnicalInfo = {
  kapi_no: number;
  merkez: string;
  merkez_tipi: string;
  kisa_bilgi: string;
  burc: string;
  burc_detay: string;
  antisya: string;
  antisya_detay: string;
};

export const GATE_TECHNICAL_DATA: Record<number, GateTechnicalInfo> = {
  1:  { kapi_no: 1,  merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Kendini ifade kapısı",       burc: "Akrep",          burc_detay: "13°15′00″ – 18°52′30″ Akrep",                        antisya: "Kova",          antisya_detay: "Akrep→Kova" },
  2:  { kapi_no: 2,  merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Yön kapısı",                 burc: "Boğa",           burc_detay: "13°15′00″ – 18°52′30″ Boğa",                         antisya: "Aslan",         antisya_detay: "Boğa→Aslan" },
  3:  { kapi_no: 3,  merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Düzen sağlama kapısı",       burc: "Koç / Boğa",     burc_detay: "26°22′30″ Koç – 02°00′00″ Boğa",                     antisya: "Başak / Aslan", antisya_detay: "Koç→Başak / Boğa→Aslan" },
  4:  { kapi_no: 4,  merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Yanıtlar kapısı",            burc: "Aslan",          burc_detay: "18°52′30″ – 24°30′00″ Aslan",                        antisya: "Boğa",          antisya_detay: "Aslan→Boğa" },
  5:  { kapi_no: 5,  merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Kalıplar-bekleyiş kapısı",   burc: "Yay",            burc_detay: "11°22′30″ – 17°00′00″ Yay",                          antisya: "Oğlak",         antisya_detay: "Yay→Oğlak" },
  6:  { kapi_no: 6,  merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Çatışma kapısı",             burc: "Başak",          burc_detay: "22°37′30″ – 28°15′00″ Başak",                        antisya: "Koç",           antisya_detay: "Başak→Koç" },
  7:  { kapi_no: 7,  merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Liderlik kapısı",            burc: "Aslan",          burc_detay: "13°15′00″ – 18°52′30″ Aslan",                        antisya: "Boğa",          antisya_detay: "Aslan→Boğa" },
  8:  { kapi_no: 8,  merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Katkı kapısı",               burc: "Boğa / İkizler", burc_detay: "24°30′00″ Boğa – 00°07′30″ İkizler",                 antisya: "Aslan / Yengeç",antisya_detay: "Boğa→Aslan / İkizler→Yengeç" },
  9:  { kapi_no: 9,  merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Odaklanma kapısı",           burc: "Yay",            burc_detay: "05°45′00″ – 11°22′30″ Yay",                          antisya: "Oğlak",         antisya_detay: "Yay→Oğlak" },
  10: { kapi_no: 10, merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Benlik sevgisi",             burc: "Yay / Oğlak",    burc_detay: "28°15′00″ Yay – 03°52′30″ Oğlak",                    antisya: "Oğlak / Yay",   antisya_detay: "Yay→Oğlak / Oğlak→Yay" },
  11: { kapi_no: 11, merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Fikirler kapısı",            burc: "Yay",            burc_detay: "22°37′30″ – 28°15′00″ Yay",                          antisya: "Oğlak",         antisya_detay: "Yay→Oğlak" },
  12: { kapi_no: 12, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "İhtiyat kapısı",             burc: "İkizler",        burc_detay: "22°37′30″ – 28°15′00″ İkizler",                      antisya: "Yengeç",        antisya_detay: "İkizler→Yengeç" },
  13: { kapi_no: 13, merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Dinleyici kapısı",           burc: "Kova",           burc_detay: "13°15′00″ – 18°52′30″ Kova",                         antisya: "Akrep",         antisya_detay: "Kova→Akrep" },
  14: { kapi_no: 14, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Güç becerileri kapısı",      burc: "Akrep / Yay",    burc_detay: "24°30′00″ Akrep – 00°07′30″ Yay",                    antisya: "Kova / Oğlak",  antisya_detay: "Akrep→Kova / Yay→Oğlak" },
  15: { kapi_no: 15, merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Aşırı uçlar kapısı",         burc: "İkizler / Yengeç",burc_detay: "28°15′00″ İkizler – 03°52′30″ Yengeç",               antisya: "Yengeç / İkizler",antisya_detay: "İkizler→Yengeç / Yengeç→İkizler" },
  16: { kapi_no: 16, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Beceriler kapısı",           burc: "İkizler",        burc_detay: "05°45′00″ – 11°22′30″ İkizler",                      antisya: "Yengeç",        antisya_detay: "İkizler→Yengeç" },
  17: { kapi_no: 17, merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Kanılar kapısı",             burc: "Koç",            burc_detay: "03°52′30″ – 09°30′00″ Koç",                          antisya: "Başak",         antisya_detay: "Koç→Başak" },
  18: { kapi_no: 18, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Düzeltme kapısı",            burc: "Terazi",         burc_detay: "03°52′30″ – 09°30′00″ Terazi",                       antisya: "Balık",         antisya_detay: "Terazi→Balık" },
  19: { kapi_no: 19, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "İstemek kapısı",             burc: "Kova",           burc_detay: "07°37′30″ – 13°15′00″ Kova",                         antisya: "Akrep",         antisya_detay: "Kova→Akrep" },
  20: { kapi_no: 20, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Başkalaşım kapısı",          burc: "İkizler",        burc_detay: "00°07′30″ – 05°45′00″ İkizler",                      antisya: "Yengeç",        antisya_detay: "İkizler→Yengeç" },
  21: { kapi_no: 21, merkez: "Kalp-İrade",    merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Haznedar kapısı",            burc: "Koç",            burc_detay: "09°30′00″ – 15°07′30″ Koç",                          antisya: "Başak",         antisya_detay: "Koç→Başak" },
  22: { kapi_no: 22, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Zarafet kapısı",             burc: "Balık",          burc_detay: "17°00′00″ – 22°37′30″ Balık",                        antisya: "Terazi",        antisya_detay: "Balık→Terazi" },
  23: { kapi_no: 23, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Özümseme kapısı",            burc: "Boğa",           burc_detay: "18°52′30″ – 24°30′00″ Boğa",                         antisya: "Aslan",         antisya_detay: "Boğa→Aslan" },
  24: { kapi_no: 24, merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Rasyonelleştirme kapısı",    burc: "Boğa",           burc_detay: "07°37′30″ – 13°15′00″ Boğa",                         antisya: "Aslan",         antisya_detay: "Boğa→Aslan" },
  25: { kapi_no: 25, merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Masumiyet kapısı",           burc: "Balık / Koç",    burc_detay: "28°15′00″ Balık – 03°52′30″ Koç",                    antisya: "Terazi / Başak",antisya_detay: "Balık→Terazi / Koç→Başak" },
  26: { kapi_no: 26, merkez: "Kalp-İrade",    merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Düzenbaz kapısı",            burc: "Yay",            burc_detay: "17°00′00″ – 22°37′30″ Yay",                          antisya: "Oğlak",         antisya_detay: "Yay→Oğlak" },
  27: { kapi_no: 27, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Sorumluluk kapısı",          burc: "Boğa",           burc_detay: "02°00′00″ – 07°37′30″ Boğa",                         antisya: "Aslan",         antisya_detay: "Boğa→Aslan" },
  28: { kapi_no: 28, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Mücadele kapısı",            burc: "Akrep",          burc_detay: "02°00′00″ – 07°37′30″ Akrep",                        antisya: "Kova",          antisya_detay: "Akrep→Kova" },
  29: { kapi_no: 29, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Sebat kapısı",               burc: "Aslan / Başak",  burc_detay: "24°30′00″ Aslan – 00°07′30″ Başak",                  antisya: "Boğa / Koç",    antisya_detay: "Aslan→Boğa / Başak→Koç" },
  30: { kapi_no: 30, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Arzu kapısı",                burc: "Kova / Balık",   burc_detay: "24°30′00″ Kova – 00°07′30″ Balık",                   antisya: "Akrep / Terazi",antisya_detay: "Kova→Akrep / Balık→Terazi" },
  31: { kapi_no: 31, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Demokrasi kapısı",           burc: "Aslan",          burc_detay: "02°00′00″ – 07°37′30″ Aslan",                        antisya: "Boğa",          antisya_detay: "Aslan→Boğa" },
  32: { kapi_no: 32, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Devamlılık kapısı",          burc: "Terazi",         burc_detay: "20°45′00″ – 26°22′30″ Terazi",                       antisya: "Balık",         antisya_detay: "Terazi→Balık" },
  33: { kapi_no: 33, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Mahremiyet kapısı",          burc: "Aslan",          burc_detay: "07°37′30″ – 13°15′00″ Aslan",                        antisya: "Boğa",          antisya_detay: "Aslan→Boğa" },
  34: { kapi_no: 34, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Güç kapısı",                 burc: "Yay",            burc_detay: "00°07′30″ – 05°45′00″ Yay",                          antisya: "Oğlak",         antisya_detay: "Yay→Oğlak" },
  35: { kapi_no: 35, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Değişim kapısı",             burc: "İkizler",        burc_detay: "11°22′30″ – 17°00′00″ İkizler",                      antisya: "Yengeç",        antisya_detay: "İkizler→Yengeç" },
  36: { kapi_no: 36, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Kriz kapısı",                burc: "Balık",          burc_detay: "22°37′30″ – 28°15′00″ Balık",                        antisya: "Terazi",        antisya_detay: "Balık→Terazi" },
  37: { kapi_no: 37, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Dostluk kapısı",             burc: "Balık",          burc_detay: "05°45′00″ – 11°22′30″ Balık",                        antisya: "Terazi",        antisya_detay: "Balık→Terazi" },
  38: { kapi_no: 38, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Savaşçı kapısı",             burc: "Oğlak",          burc_detay: "09°30′00″ – 15°07′30″ Oğlak",                        antisya: "Yay",           antisya_detay: "Oğlak→Yay" },
  39: { kapi_no: 39, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Kışkırtma kapısı",           burc: "Yengeç",         burc_detay: "09°30′00″ – 15°07′30″ Yengeç",                       antisya: "İkizler",       antisya_detay: "Yengeç→İkizler" },
  40: { kapi_no: 40, merkez: "Kalp-İrade",    merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Yalnızlık kapısı",           burc: "Başak",          burc_detay: "05°45′00″ – 11°22′30″ Başak",                        antisya: "Koç",           antisya_detay: "Başak→Koç" },
  41: { kapi_no: 41, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Azalma kapısı",              burc: "Kova",           burc_detay: "02°00′00″ – 07°37′30″ Kova",                         antisya: "Akrep",         antisya_detay: "Kova→Akrep" },
  42: { kapi_no: 42, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Bitirme kapısı",             burc: "Koç",            burc_detay: "20°45′00″ – 26°22′30″ Koç",                          antisya: "Başak",         antisya_detay: "Koç→Başak" },
  43: { kapi_no: 43, merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "İç görü kapısı",             burc: "Akrep",          burc_detay: "18°52′30″ – 24°30′00″ Akrep",                        antisya: "Kova",          antisya_detay: "Akrep→Kova" },
  44: { kapi_no: 44, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Karşılayıcı-enerji kapısı",  burc: "Akrep",          burc_detay: "07°37′30″ – 13°15′00″ Akrep",                        antisya: "Kova",          antisya_detay: "Akrep→Kova" },
  45: { kapi_no: 45, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Kral ya da kraliçe kapısı",  burc: "İkizler",        burc_detay: "17°00′00″ – 22°37′30″ İkizler",                      antisya: "Yengeç",        antisya_detay: "İkizler→Yengeç" },
  46: { kapi_no: 46, merkez: "Benlik G",      merkez_tipi: "Kimlik/Yön Merkezi",              kisa_bilgi: "Beden sevgisi",              burc: "Başak / Terazi", burc_detay: "28°15′00″ Başak – 03°52′30″ Terazi",                  antisya: "Koç / Balık",   antisya_detay: "Başak→Koç / Terazi→Balık" },
  47: { kapi_no: 47, merkez: "Zihin",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Kavrayış kapısı",            burc: "Başak",          burc_detay: "17°00′00″ – 22°37′30″ Başak",                        antisya: "Koç",           antisya_detay: "Başak→Koç" },
  48: { kapi_no: 48, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Derinlik kapısı",            burc: "Terazi",         burc_detay: "09°30′00″ – 15°07′30″ Terazi",                       antisya: "Balık",         antisya_detay: "Terazi→Balık" },
  49: { kapi_no: 49, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Devrim kapısı",              burc: "Kova",           burc_detay: "18°52′30″ – 24°30′00″ Kova",                         antisya: "Akrep",         antisya_detay: "Kova→Akrep" },
  50: { kapi_no: 50, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Değerler kapısı",            burc: "Terazi / Akrep", burc_detay: "26°22′30″ Terazi – 02°00′00″ Akrep",                  antisya: "Balık / Kova",  antisya_detay: "Terazi→Balık / Akrep→Kova" },
  51: { kapi_no: 51, merkez: "Kalp-İrade",    merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Şok kapısı",                 burc: "Koç",            burc_detay: "15°07′30″ – 20°45′00″ Koç",                          antisya: "Başak",         antisya_detay: "Koç→Başak" },
  52: { kapi_no: 52, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Hareketsizlik kapısı",       burc: "Yengeç",         burc_detay: "03°52′30″ – 09°30′00″ Yengeç",                       antisya: "İkizler",       antisya_detay: "Yengeç→İkizler" },
  53: { kapi_no: 53, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "İlerleme kapısı",            burc: "Yengeç",         burc_detay: "15°07′30″ – 20°45′00″ Yengeç",                       antisya: "İkizler",       antisya_detay: "Yengeç→İkizler" },
  54: { kapi_no: 54, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Dürtü kapısı",               burc: "Oğlak",          burc_detay: "15°07′30″ – 20°45′00″ Oğlak",                        antisya: "Yay",           antisya_detay: "Oğlak→Yay" },
  55: { kapi_no: 55, merkez: "Solar Pleksus", merkez_tipi: "Motor + Farkındalık Merkezi",     kisa_bilgi: "Ruh kapısı",                 burc: "Balık",          burc_detay: "00°07′30″ – 05°45′00″ Balık",                        antisya: "Terazi",        antisya_detay: "Balık→Terazi" },
  56: { kapi_no: 56, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Öykücü kapısı",              burc: "Yengeç / Aslan", burc_detay: "26°22′30″ Yengeç – 02°00′00″ Aslan",                  antisya: "İkizler / Boğa",antisya_detay: "Yengeç→İkizler / Aslan→Boğa" },
  57: { kapi_no: 57, merkez: "Dalak",         merkez_tipi: "Farkındalık Merkezi",             kisa_bilgi: "Sezgi kapısı",               burc: "Terazi",         burc_detay: "15°07′30″ – 20°45′00″ Terazi",                       antisya: "Balık",         antisya_detay: "Terazi→Balık" },
  58: { kapi_no: 58, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Sevinç kapısı",              burc: "Oğlak",          burc_detay: "03°52′30″ – 09°30′00″ Oğlak",                        antisya: "Yay",           antisya_detay: "Oğlak→Yay" },
  59: { kapi_no: 59, merkez: "Sakral",        merkez_tipi: "Motor Merkezi",                   kisa_bilgi: "Cinsellik kapısı",           burc: "Başak",          burc_detay: "00°07′30″ – 05°45′00″ Başak",                        antisya: "Koç",           antisya_detay: "Başak→Koç" },
  60: { kapi_no: 60, merkez: "Kök",           merkez_tipi: "Baskı + Motor Merkezi",           kisa_bilgi: "Kabullenme kapısı",          burc: "Oğlak / Kova",   burc_detay: "26°22′30″ Oğlak – 02°00′00″ Kova",                   antisya: "Yay / Akrep",   antisya_detay: "Oğlak→Yay / Kova→Akrep" },
  61: { kapi_no: 61, merkez: "Taç",           merkez_tipi: "Baskı Merkezi",                   kisa_bilgi: "Gizem kapısı",               burc: "Oğlak",          burc_detay: "20°45′00″ – 26°22′30″ Oğlak",                        antisya: "Yay",           antisya_detay: "Oğlak→Yay" },
  62: { kapi_no: 62, merkez: "Boğaz",         merkez_tipi: "İfade/Manifestasyon Merkezi",     kisa_bilgi: "Ayrıntılar kapısı",          burc: "Yengeç",         burc_detay: "20°45′00″ – 26°22′30″ Yengeç",                       antisya: "İkizler",       antisya_detay: "Yengeç→İkizler" },
  63: { kapi_no: 63, merkez: "Taç",           merkez_tipi: "Baskı Merkezi",                   kisa_bilgi: "Kuşku-şüphe kapısı",         burc: "Balık",          burc_detay: "11°22′30″ – 17°00′00″ Balık",                        antisya: "Terazi",        antisya_detay: "Balık→Terazi" },
  64: { kapi_no: 64, merkez: "Taç",           merkez_tipi: "Baskı Merkezi",                   kisa_bilgi: "Şüphe kapısı",               burc: "Başak",          burc_detay: "11°22′30″ – 17°00′00″ Başak",                        antisya: "Koç",           antisya_detay: "Başak→Koç" },
};

export function getGatesFromChannels(channels: string[]): number[] {
  const gateNums: number[] = [];
  for (const ch of channels) {
    const parts = ch.split("-");
    for (const p of parts) {
      const n = parseInt(p, 10);
      if (!isNaN(n) && n >= 1 && n <= 64) gateNums.push(n);
    }
  }
  return gateNums;
}

export function resolveUniqueGates(gates: number[], channels: string[]): number[] {
  const fromChannels = getGatesFromChannels(channels);
  return [...new Set([...gates, ...fromChannels])].sort((a, b) => a - b);
}
