// FAZ 4 — Zamanlama yorum katalogları. Kaynak: kitap 1. seviye (verbatim, uydurma YOK).
// Universal Month/Day, Personal Month/Day katalog metnini semantic-context ile reuse eder.
export const UNIVERSAL_YEAR_CATALOG: Record<number, string> = {
  1: `Yeni başlangıçlar ve eylem`,
  2: `İşbirliği ve denge`,
  3: `İletişim ve ifade etme`,
  4: `İnşa etme ve planlama`,
  5: `Hareket ve değişiklik`,
  6: `sorumluluk ve evrensel sevgi`,
  7: `İçe bakış ve kişisel olgunlaşma`,
  8: `Karmik adalet ve güç`,
  9: `Sonlar ve tamamlanmalar Sadece evrensel yıl sayısı yoktur.`,
};

export const PERSONAL_YEAR_CATALOG: Record<number, string> = {
  1: `Bu sene, geçmişe sünger çekebilir ve yepyeni bir 9senelik döngüye kendinizi ve yaşam kalitesini geliştirmek için niyet edebilirsiniz. Bu sene yapacağınız her şeyi ve bunları yaparken takındığınız tutum, gelecek dokuz senenin gidişatını belirleyecektir. Bu nedenle bu dönemde olumlu bir anlayış oluşturmalı ve gelişim göstermek için etkin bir tutum sergilemelisiniz. Bu sene büyük şanslar ve yeni fırsatlarla karşılaşacaksınız bu nedenle işlerinizi daha sonraya bırakmayın yoksa çok büyük fırsatları kaçırabilirsiniz. Bir sayısının eril enerjisi, sizi karar verici olmak ve harekete geçmek yönünde cesaretlendirecektir. Bu sayede siz yenilenmiş enerjiler ve yeni fikirlerin akınına uğradığınızı deneyimleyeceksiniz. 12 ay içinde meyve verebilmeleri için bu fikirlere yeterli zaman vererek onları terbiye etmeniz ve onları yetiştirmeniz çok önemlidir. Her ne yaparsanız yapın, isteklerini doğrudan gerçekleşmiyorsa, asla vazgeçmeyin. Aynı anda hem etkin hem de sabırlı olmanız gerekir. Sezgilerinize yükseltmek için düzenli meditasyon yapın. Bu sayede hangi mantıklı adımları atmanız gerektiğini ve iyi fikirlerle, zaman kaybı olanları birbirinden ayırmayı öğrenebilirsiniz.`,
  2: `Kişisel yıl sayısı olan iki, istikrar sağlama ve daha önce yarattıklarını de ve size gelmesini beklediklerinizi birleştirmekle ilgilidir. Bu sene o kadar yavaş bir tempoda ilerleyecek ki, neredeyse hiçbir şeyin ilerlemediğini hissedeceğiniz zamanlar olacak. Ancak bu hareketsizliğe kanmayın, hala sahne arkasında bir şeyler olmaya devam ediyor. İşler durma noktasına gelebilir, paniklemeyin. Evren, geçen seneki değişimlerde gelişimlere kuvvetlenmeleri ve olgunlaşmaları için ihtiyaç duydukları zamanı veriyor. Bu sırada siz şimdi yaşayın ve onunla bir zihin durumu sağlayan, sakinleştirici temel pratiklerden faydalanın. Bu süre zarfında sevdiğiniz müzikleri dinlemek, şarkı söylemek, yazmak ya da çalmakta oldukça yararlı olacaktır. Aşk, ilişkiler, duygular ve kaygı ile ilgili SORUNLAR bu sene öne çıkacaktır. Mevcut ilişkilerinizde güçlükler ortaya çıkacak ya da var olan ilişkiler daha da güçlenecektir. Yalnız olanlar özel bir kişiyle tanışabilirler. Genellikle iki senesinde gerçekleşen olaylar; samimi sevgi, ruhu ikizi ile karşılaşmak, aşk acısı, derin bağlar kurmak, mutluluk ve neşedir. Ayrıca kendinize olan sevgiye odaklanmanız gereken ve kendinizle güçlü bir ilişki kurmanız gereken de bir senedir. Hayatınızdaki her alanda dengeyi sağlamak için çabalayın.`,
  3: `Bu sene, sizin sonunda ettiğinizi biçmeye başlayacağınız bir sene. Olan biten bir çok şey olacak ve bu nedenle planlama, disiplin ve odaklanma açısından ekstra emek harcamanız gerekecek. Eğer enerjinizi çok fazla konuya dağıtırsınız ya da her tarakta beziniz olursa, işler kolayca kontrolden çıkar ve bu da hiçbir konuyu tamamlayamamanıza neden olabilir. Sizi başarıya götüren anahtar düzenli ve aklı başında olmaktır. Üç senesi, sosyal olmayı ve başkalarıyla zaman geçirmeyi gerektiren, eski arkadaşlarla tekrar bağ kurmaya ve yeni arkadaşlar edinmeye açık olmak gereken bir senedir. Sosyal takviminiz oldukça canlanacak ve bu nedenle içinizde insanları eğlendirme arzusu bulabileceğiniz gibi, kalabalıklara ve organizasyonlara katılmayı da arzu edeceksiniz. Eğer üzerinde çalışmak istediğiniz yaratıcı bir proje varsa, şimdi bunu yapmanın tam zamanı. Bu sene, neşe ve eğlence temalarının daha üstün geleceği, neşeli bir sene olacak. Bu dönemde ne yaptığınızdan ziyade nelerden zevk aldığınız daha önemli olacak. İster tatile gitmek olsun, ister bahçeyle uğraş Mak, yemek yapmak, dans etmek, müzik dinlemek ya da hobi üzerine zaman geçirmek olsun, sizi iyi hissettiren her şeyin daha fazlasını yapın.`,
  4: `Kişisel yıl sayısı 4 , yaşantınızı olabileceğinin en iyisi haline getirebilmeniz için yapmanız gerekenleri yapmanızla ilgilidir. Bu yıl, sizin gelecek hedeflerinizi planlayacaksınız ve bunları başarmak için adımlar atacağınız bir senedir. Gelecek 12 ay, hayat size geleceğiniz için sağlam temeller inşa etme fırsatı verecektir. Bunu boşa harcamayın. Bu sene bir çok konuyu başaracaksın ve büyük ilerlemeler kaydedeceksiniz. Ama başarınızın anahtarı daima tutumunuzdur. Engellerle, hayal kırıklıkları ve gecikmelerle karşılaşabilirsiniz ancak sabır ve sebat ile sonunda istediklerinizi ulaşacaksınız. Bu sene, sizin kendinize adamınız ve azmini sunacaktır bu yüzden işler zorlaştığında başarmak istediklerinizden vazgeçmemelisiniz. Sadece toparlanıp yolunuza devam etmelisiniz. Bu yıl boyunca köklerinizi sağlığınız ve geleceğinizi oluşturduğunuz günlerle dolu geçecek. Bu nedenle, bu dönem para biriktirmek, borçları ödemek, ilişkileri sağlamlaştırmak ve aile veya bir iş kurmak ya da ev almak için oldukça iyi bir dönemdir. Bu dönem sizin ekstra Fiziksel, zihinsel ya da duygusal emek sarf etmeniz gerekiyor ve ama emekler karşılığında ödüller gelecektir. Eğer olumlu bir zihin halinde olursanız, bu sene sizin için oldukça kayda değer bir sene olacaktır.`,
  5: `Bir önceki sene verilen emekler ve çok çalışma sayesinde artık dinamik ve aksiyon dolu bir yıla ve beklenen ya da beklenmeyen değişimlere giriş yapmış bulunuyorsunuz. Bu yıl değişim kaçınılmazdır ve bunu birçok şekilde gerçekleştirebilirsiniz. Bazı insanlar için yer, ikamet, ilişki ya da iş değişikliği olabilirken, diğerleri için tutum, yön ya da yaşam tarzı değişikliği söz konusu olabilir. Her şekilde seçilmesi gereken birçok tercihi olacak bu nedenle eski alışkanlıklardan vazgeçmeli ve kendinizi yeni bir mücadele ve gelişme alanına hazır etmelisiniz. Bu dönemde aceleci kararlar almayın, harekete geçmeden önce düşünün. Yemek, alkol, fazla para harcama ya da macera duygularınızı tatmine karşı aşırı bir ilgi duyabilirsiniz. Bu nedenle aşırıya kaçmadan ve riske girmeden Ölçülü ve disiplinli olmaya dikkat edin. Seyahat etmek, keşfetmek ve maceralara girmek bu sene odak noktanız olacak. Beş senesi, sizin zihin durumunuza göre canlandırıcı yeten mücadele edilecek bir sene olabilir. 5 SENESİNDE YAPILMASI GEREKENLER • Değişiklikler yapan ve değişikliklere hazırlıklı olun. • Kendinize daha fazla kişisel özgürlük alanı yaratın. • Yeni şeyler deneyimleyin, neşeli ve maceraperest olun. • Ulusal ya da uluslararası seyahatler yapın. • Kendinizi tanıtın, sosyal olun ve başkalarıyla ağ kurun. • İşinizi ya da kariyerinizi değiştirin. • Hesaplanmış riskler alın. ҉`,
  6: `Altı kişisel yıl sayısı, başkalarına yardımcı olmak ve sorumluluklarını yerine getirme senesidir. Biraz fedakârlık içerebilir, bu nedenle başkalarının ihtiyaçlarını kendinizinkinin önüne koymaya hazırlıklı olun. Başkalarına yardım etmek ile yardım etmek zorunda olmak arasında çok büyük bir fark vardır. Bu sene en çok bu ayrımı yansıtacaktır. Önümüzdeki bu 12 ay boyunca sevdikleriniz ve ailenize ön plana alacaksınız, bu nedenle onları kendi isteğinizle yardım etmeye çalışın. Bu dönem, bozulan ilişkilerinizi düzeltmek ve bir süredir görüşmediğiniz aile bireyleri ile görüşmeniz için mükemmel bir zamandır. Ailenizdeki çocuklara da ekstra zaman ayırma dönemidir. Altı sayısı sevgiye, evliliği, ayrıldığı ve boşanmayı yönetir. Bazı kimseler hayatlarındaki bu gelişmeleri hep altı senesinde yaşamışlardır. Herhangi bir topluluk projesine katılmak, çocuk sahibi olmak, hizmet tabanlı bir kariyere başlamak ya da evden çalışmaya başlayarak bu yılı geçirebilirsiniz. 6 senesi; Bahçenizle, evinizde kendi güzellik ve fiziksel görünüşünüzle ilgilenmeyi de temsil eder. Görünümünüzü değiştirme, dolabınızı yenileme ya da saç sitilini değiştirmeyle özgüvenimizi güçlendirebilirsiniz.`,
  7: `Bu sene kendinizle daha iyi ilişkiler kurmaya odaklanacaksınız. Yedi kişisel yıl sayısı, kişiyi, kendisini analiz etme konusunda destekler. Böylece siz kim olduğunuzu, ne istediğinizi ve neden burada olduğunuz konusunda bir anlayış geliştirirsiniz. Önümüzdeki 12 ay boyunca esas gündeminiz kişisel gelişim, spiritüel bilgelik ve aradığınız cevapları kendi içinizde bulmak olacaktır. Yeni fırsatlar kovalamak ya da iç dünyasını ele geçirmek zamanı değildir. Bunun yerine bir adım geride durmak ve düşünüp taşınma zamanıdır. Ne kadar çok iç dünyanızda iş yaparsanız, gelecek sene yani sekiz kişisel yılınız da dış dünyada o kadar başarı sağlarsınız. Eğer bir önceki sene bir kayıp ya da kalp kırıklığı yaşamışsınız bu seneyi şifa bulma süreci olarak kullanabilirsiniz. Eğer bu yola meyilli hissediyorsanız, alternatif terapileri keşfedebilirsiniz. Bu sene hiçbir şeyi gerçekleştirmek için zorlamayın, istediklerinizin size gelmesini bekleyin. Fırsatlar, bir sonraki sene size kendilerini göstereceklerdir. Gelecek yıllara hazırlık için güçlü bir içsel temel kurun. Gelecek yıllardaki başarınız, bu sene yaptığınız olumlu değişikliklerde gizlidir.`,
  8: `Sekiz kişi sayısı ise iş, kariyer, mülkiyet, finans ve yasak onları odaklanmaktadır. Bazıları için muhteşem kariyer yükseltme fırsatları, itibar ve finansal kazançlar ortaya çıkarken, bazıları giderlerini arttığını gece finansal zararları deneyimleyebilirler. Her iki türlü de sekiz, adalet terazisinin kefelerini tekrar dengeleyen, karmik bir denge sayısıdır. Sizin geçmişteki tutum ve eylemlerinizle, özellikle bir kişisel yılınız da yaptıklarınızla doğrudan orantılıdır.8 senesi içinde ektiklerinizi biçersiniz ve birinci senenizde neye başladıysanız, artık onun için geri ödeme yapma zamanıdır. Eğer dürüst ve çalışkan olduysanız, bir şekilde finansal ya da itibari ya da onunla fırsatlarla ödüllendirileceksinizdir. Bu sene tamamen denge ile özellikle maddi ve spiritüel dünyaların dengelenmesi ile ilgilidir. Bir tarafta para ile olumlu ilişkiler kurmaya cesaretlendirilir ve bereketi kendinize çekecek bir tutum elde edersiniz, diğer yandan para birikimi ve maddi eşyalar, güç, statü ya da başarı tarafından tüketilecek duruma gelmemek için kendinize dikkat edersiniz. Yaşantınızda hangi konuda dengede değilseniz, sekiz yılı size onu işaret edecek ve bunu yeniden dengeleme fırsatı verecektir.`,
  9: `Bu sene, son dokuz senelik döngünün son senesidir ve bu sene, tamamlanmaya ve dönüşme odaklanarak yeni başlangıçlara hazırlanma dönemidir. Bu dönüşümün büyük bir kısmı iş, arkadaşlık ya da herhangi bir ilişki, konut, tutum ya da davranış gibi çoktan aşmış olabileceğiniz ve artık sizin yaşamınıza hizmet etmeyen şeylerin hayatınızdan çıkmasına izin vermenizden oluşur. Her türlü bu dönem sizin hayatınızdaki bahar temizliği gibidir ve böylece daha iyi şeylere doğru ilerlemeniz mümkün hale gelir. Bu seneden az emi derecede faydalanmak için inancınızda güvenin, değişime teslim olun, diğerlerini ve kendinize affedin. Bu sene bitişlerin senesi olsa da, aynı zamanda çabaladığınız her şeyin meyvesini alacağınız bir yeniden doğuş ve telafi senesidir de. Bir diğer değişle, bu sene sizin hesap kapatma seneniz, bu yüzden bu yılı değerli ve önemli hissetmeye başlamalısınız. Dokuz senesi çevrenizdekilere yardım etmek ve yardımsever uğraşlar için zaman, para, ilgi harcamak ya da iyi bir amaç uğruna istenmeyen eşyaları kullanmak konusunda sizi cesaretlendirir. Yardım dernekleri,hayvan barınakları, yardıma muhtaç bir aileyle ilgilenmek için iyi zamanlardır.`,
};

export const PERSONAL_MONTH_CATALOG: Record<number, string> = {
  1: `• Bu ay, harekete geçeceğiniz ve yeni şeylere başlayacağınız bir aydır. Yeni fırsatlar kendilerini gösterecekler, bunları değerlendirmekten çekinmemelisiniz. Yine bu dönem hırslı, azimli ve kararlı olmak ve yaşamınızı yönetmeniz, idari ele almanız için iyi bir zamandır. Değişiklikler yapmak, yenilikler getirmek ve yeni şeyler denemek konusunda cesaretli olun`,
  2: `Bu ay bir adım geride durup sabırlı olma ayıdır. İstediklerinizi gerçekleşmesi için zorlamamalısınız. Şimdiye kadar yapmış olduklarınızda istikrar sağlayan ve görünenin ardında kalan daha iyi detaylar üzerine çalışın. İlişkilerinizde denge, huzur ve uyumu arayın ve diğer insanlara karşı yardımsever olun. Geçmişten kalma yaralarınızı iyileştiren, duygularinizi sağlıklı bir yoldan ifade edin ve sevgi alıp vermeye açık olun.`,
  3: `• Bu ay yaşamınıza biraz daha mutluluk katacak ve sizi neşelendirir en şeyleri daha çok yapacağınız bir ay. Sosyal olun, arkadaşlarınızla vakit geçiren, eğlenin ve yaratıcı uğraşlarla amatörce de olsa ilgilenin. Yaşamınızda neler olduğunun hiçbir önemi yok. Önemli olan sizin iyimser bir tutum içinde olmanız. Bu dönem ayrıca kendinizi ifade ettiğiniz, duygu ve düşüncelerini dürüstçe ifade edebileceğiniz bir zamandır.`,
  4: `• Bu ay iş ve kişisel yaşamlarını de düzene sokmanızın iyi olacağı bir aydır. Düzenli ve odaklanmış ve etkin olan. Henüz bitirmediğiniz herhangi bir projenize bitirmeye odaklanın. Yaşamınızın her alanında sıkı çalışmanız gereken ve emek sarf etmeniz gereken bir dönemdesiniz. Emeklerinizin karşılığında ödüllendirileceksiniz. İstikrar sağlayın ve sağlam bir zemin inşa edin. Geleceği planlayın, hiçbir şeyi sürüncemede bırakmayın yada vaktinizi boşa harcamayın. Mücadele ettiğiniz şeylerde sonuna kadar direnin ve asla pes etmeyin.`,
  5: `• Bu ay koruma alanınızdan çıkmanız, maceracı bir tutum sergilemeniz ve yeni şeyler denemeniz için iyi bir zaman. Esnek ve uyumlu olan, kendinizi değişime hazırlayın. Eğer yaşamınızda yapmanız gereken değişiklikler varsa, bu ay bunları gerçekleştirmek için tam zamanı. Bu ay, oldukça dinamik ve hızlı bir ay olacak. Bu nedenle odaklanın ve önceliklerinizi ve Zamanınızı doğru değerlendirin. Her işte parmağınız olması gerekmiyor. Sosyal olun ve kendinizi yüceltin.`,
  6: `Bu ay özellikle eviniz, ilişkileriniz ve ailenizle olan yükümlülüklerinisi yerine getireceğiniz ve sorumluluk alacağınız bir ay olacak.sizden yardım, ilgi ya da zaman ayırmanızı bekleyen kişilere karşı vakit ayırın ve çocuklarınızla kaliteli zaman geçirin. Başkaları ile ilgili henüz çözülmemiş problemler açığa çıkabilir. Bu dönem ilişkilerinizi geliştirmeniz ve sevgi alıp vermeye odaklanacağınız bir dönemdir.`,
  7: `• Bu ay hayatın karmaşasından bir adım geride durup enerjinizi doldurmanız gereken bir aydır. Kendi başınıza sessizce zaman geçiren ve yaşam amacınız, yaşamınızı nasıl geliştirebileceğiniz üzerine derin düşüncelere dalın. Spiritüel tarafınızla iletişime geçme ve daha iyi bir insan olmaya odaklandığınız bir dönemdesiniz.Sağlığınızı iyileştirmeye ve yoga, meditasyon gibi alternatif çalışmaları keşfedin.`,
  8: `• Bu ay bütçe yapmalı ve finansal durumunuzu düzenlemelisiniz. Sıkı çalışın ve çok fazla para harcamayın. Bir kariyer fırsatı ortaya çıkabilir ya da ani para kazanabilir ya da harcamak durumunda kalabilirsiniz. Bu dönem kariyer değişiklikleri için oldukça uygundur. Hırslı olun, haklarınızı koruyan ve eyleme geçin. Bereketi çeken ve olumlu tutum da olun çünkü sekiz sayısı gerçekleştirme sayısıdır.`,
  9: `Bu ay bitişlerin ve dönüşümün ayıdır. Bu nedenle yeni olanın size gelebilmesi için, yolu açmak için eskiyi serbest bırakın. Kötü alışkanlıkların, insanları ve daha fazla hayatınızda ihtiyacınız olmayan her şeyi serbest bırakın. Hiçbir şeyin sona ermesinden korkmayın çünkü her zaman daha iyi fırsatlar kapıdadır. Bu ay ayrıca başkalarına yardımcı olma ayıdır. İhtiyaç duyan bir kişiye paranızı, desteğinizi ya da zamanınızı, iyi bir amaç uğruna vermeye gönüllü olabilirsiniz. Yaşamınızdaki talihsizlikleri affedin ve yolunuza devam edin.`,
};

export const PERSONAL_DAY_CATALOG: Record<number, string> = {
  1: `Engellere, sorunlara karşı koymak için uygun bir zaman. Eyleme geçmeyi kolaylaştırır ve öncülük etme isteği ile ilgili her konuda yarar sağlar. Mücadele ruhuna çok elverişlidir.`,
  2: `Aykırılık sayısı... Her şey birleşmeye ya da kopmaya bağlıdır. Ortaklaşa çalışma arayışına ya da birleşmeye çok elverişli. Karmaşa tehlikesi ve bundan ileri gelen müzakereye elverişsiz anlaşmazlıklar ortaya çıkabilir.`,
  3: `Yürütülen eylemlerin ve girişimlerin sonucu üzerinde çok etkili olan görüşmelere ve ilişkilere çok elverişli. Yalnızlık ve kendini soyutlama reddedilmelidir. Boş zamanı değerlendirici, etkinliklere çok elverişli olan bu dönemde gergin anlar da yaşanır. Bu dönemde ön plana geçmek, kişi kendini dağıtmadığı sürece, olumlu bir davranıştır.`,
  4: `Emek ve çalışma zamanı. Kamu işlerini, kişisel işlerin aleyhine olacak biçimde, birinci plana almamak gerekir. Duygusal alanda olduğu kadar, mesleki etkinlikler alanında da engeller ve sıkıntılar pek çoktur. Genelde kısıtlayıcı ve önlem ile dikkat gerektiren bir dönem.`,
  5: `Atılganlık denetlenmesi gereken bir unsurdur, çünkü hakim olunmazsa tehlikeli olabilir. Değişikliklere, yeni yönelimlere, yer değiştirmelere, yolculuklara elverişli olan 5 sayısı, olumlu anlamda varoluşu etkileme eğilimi gösterir. Yeni ilişkilere çok elverişli olan bu 5 dönemi duygusal karşılaşmaları kolaylaştırır.`,
  6: `Uzun süreli duygusal birliktelikler dönemidir. Aynı zamanda dostluk, uyum ve uzlaşma dönemidir. Toplum, yaşamına ve ev aramaya çok elverişli bir zamandır.`,
  7: `Düşünme, sakınım, sabır ve dikkat dönemidir, özellikle mali ve maddi alanlarda. Analiz ve sentez başlıca unsurlardır. Gevşemeye, rahatlamaya, yolculuklara ve zihinsel çalışmalara elverişlidir.`,
  8: `Son derece olanaklı ve maddi ve mali işlere elverişli bir dönem. İlerlemede kolaylık. İhtiyatlı olmak gerek çünkü düşüncesizce mali alana yatırım yapma tehlikesi söz konusu. Sağlığa dikkat etmek gerek. Her türlü girişim ve etkinliğe elverişli bir dönem.`,
  9: `Özellikle yurtdışı görüşmelere ve karşılıklı ilişkilere elverişli bu dönemde zarar etme ya da bozuşma olası değilse bile tahmin edilebilir. Sinirsel gerginliğin ve önceden rayına oturtulmuş bir girişimin gerçekleşmesinin, 9 yıllık bir dönemin bitiminde önemli titreşimleri olacaktır. Aynı şey, olumlu bir yankı bulacak olan yeni hedeflerin belirlenmesi için de geçerlidir. Bencillik eğilimlerinden kaçınılmalı.`,
};

// Evre / Döngü yorumları — kaynak: kitap 2. seviye (verbatim).
export const EVRE_CATALOG: Record<number, string> = {
  1: `kendini farkettiği, kendini anlamaya çalıştığı yeni bir şeye başlamaktır.kişinin hayatına her konuda yenilik, yaratıcılık ve girişim getirir.`,
  2: `kişinin hayatına gelen yeniliklerle ilgili süreçlere adaptasyon, entegre, iş birliği ve denge getirir.`,
  3: `kişinin hayatına gelen yeniliklere duygusal durumla birlikte (evlenme, boşanma, iş hayatına atılma gibi) temel kararlar bu evrede gelir. İnsanın en doğru evlenme yaşı 18/27 yaş arasıdır. Kişi bu dönemi kaçırdıysa artık çok zorlanır evlenmekte karar vermekte.`,
  4: `kişinin hayatına gelen duygusal durumlar sonrası alınan kararlar veya girilen süreçler ile ilgili sabır gösterme ve sürece sadık kalma, aldığımız karardan vazgeçmeden yolumuzda devam etmemiz gereken evredir.Sabır, sebat, süreç burası biraz zor geçer. Dünyada uyumlama çakrasıdır. Başladığı işi bitirme, tamamlama, orayla ilgili deneyimleri alıştırma, ona verilmiş negatif duygularla ezilir, boğulur ama orayı pozitife çevirmelidir. 4.döngülerde zorlar`,
  5: `kişinin disiplinli olmakta zorlandığı, adeta hayata yeniden başladığı ancak yürüdüğü yolda 4.evreyi tamamladıktan sonar şekillenen hayatından vazgeçme eğilimi göstermeden yürümesi gereken evredir. Cesaret kırılması yaşadığı için özgürleşme duygusu getirir.`,
  6: `kişinin hayatına duygusal kararla ilişkisel yada mesleki bir Kabul ve oluşum getirir. Hem aile hayatının hem kariyer alanının artık tamamen oturup son 27 yıllık dilime gireceği ve devam ediceği hal burada belirlenir.`,
  7: `hayatı, ailesi, ilişkileri, kariyeri ve karakteri ile çevresinden Kabul gördüğü evre olup, finansal ve duygusal başarı getirir.`,
  8: `kişinin kendini gerçekleştirdiği, gücün, paranın, otoritenin elde edildiği evredir. Artık hayatında olanı biteni öğrenip bilgeliğe eriştiği, edindiği verileri de gelecek kuşaklara ve topluma aktarması gereken evredir. Ahir hayatın ilk emareleri burada görülmeye başlar. ALLAH ile direk bağlantıya geçtiğiniz ve kendinizi bulduğunuz dönemdir.`,
  9: `kişinin hayatında yeni bir döngüye hazırlık, oluşum ve kavuşumların yeni evre için tamamlanması veya içinde bulunduğun hallerin değişim göstermesi sonucu köklü değişikliklerin yaşanıcağı evredir. Insan ömrünün vefat etmesi durumda ölüm dediğimiz gerçekliğin hayatımızda vücut bulduğu evredir. Ancak insanların kader planında illa 9 evreyi tamamlaması beklenmez.`,
};

export const DONGU_CATALOG: Record<number, string> = {
  1: `Yeni başlangıç , yeni adım, yeniliğe dair ne varsa temelin atıldığı ilk yıldır. Emareleri ilk doğum yılı haricinde diğer evrelerde bir önceki evrenin 9. Yılında görülmeye başlar. Girişim ve yenilik belirten yıldır.`,
  2: `Adım atılmış olan her türlü olay, yenilik ve sürece dair kabülün, anlaşılabilirliğin,iş birliğinin ve dengenin insan hayatına geldiği yıldır.`,
  3: `Yaratıcı’nın kendi mutlak varlığı altında varlıkların çoğulluğunu temsilen hareket ve devinim enerjisini verdiği sayıdır. Hareket, devinim, girişim getirir, daha çok duygusal olayların olduğu yıllardır. Çünkü yaratıcı sizleri kadın ve erkek olarak çiftler halinde yarattım. Diyerek bizlere insanların birliktelikleri altında yaşaması gerektiğini anlattığını biliyoruz 3 sayısına sahip yıl ise bunun ilk yılıdır.`,
  4: `Bir önceki döngü yılında alınan kararların oluşuma gitmesi konusunda sabırlı ve süreç insanı olarak davranmamız gerektiğini bize haber veren yıldır. Sürece sadık kalınmalıdır, kararlardan vazgeçilmemelidir.`,
  5: `Bir önceki 4 döngü yılından sürece itimat ederek sabırlı davranan bireyin cesaret göstererek hayatında kariyer alanında değişim dönüşümleri basit düzeyde yapabileceği , sektör ve alan değiştirmeden basit atılımlarla finansal varlıkları artırma konusunda adımlar atabileceği bir döngü yılıdır. Bir süre zorlanır ancak bu dönemde kararlar alamayan cesaret edemeyen kişilerin 6-7-8 döngü yıllarında finansal zirvelere çıkamadıkları görülür. Yaratıcı enerjiyi sonuna kadar kullanıp yine yaratıcı’ya tevekkülü zorunlu kılan bir yıldır.`,
  6: `Liderlik ve cesaret gerektiren bir önceki döngü yılında yapılan yatırım, girişim ve adımların her zemine oturduğu, temellerin sağlamlaştığı ve oluşumların insan hayatına geldiği yıldır. Aynı zamanda 3-6-9-‘dan dolayı 3 enerjisinde bir yıldır.Çocuk sahibi olmalar veya çocuklarınızın evlenmesi veya bireyin bizzat kendisinin tıpkı 3 yılında olduğu gibi duygusal birliktelikleriçin oluşum temelli adımlar atması bu yılda ortaya çıkar.`,
  7: `Artık insanın bir evre içerisinde tüm olayları yaşayıp yenilik kısmında yorulmadan zorluklarla sık yüzleşmeden 6 yıllık emeğin hasadının yapılmaya başladığı ilk yıldır.Her evrenin 7. Yılı kişinin insanlar nazarında Kabul gördüğü yıldır.İspat getirir, güven getirir, bolluk getirir.`,
  8: `Bir evrenin içerisinde en bereketli en rahat yaşanan, kişinin kendini en güçlü hissettiği ancak değişimlere de yavaş yavaş başladığı ilk yıldır.Nitekim bir sonraki yılın hazırlıkları burada yapılır. 9. Döngüye ait olaylar burada şekillenir.`,
  9: `Artık bir önceki yılda alınan kararların uygulandığı, köklü değişim ve dönüşümlerin yaşandığı, yeni bir evreye geçişin ilk yılıdır aslında. Bir önceki evreyi de sonlandıran yıldır. Her türlü bitiş ve başlangıçlar için en ideal yıldır. Evlilikler, ayrılıklar, şehir ve meslek değişimleri, ülke değişimleri vb.her konuda en ideal yıldır.`,
};
