-- =============================================================================
-- 20261001000000_cupping_topic_notes.sql  —  BİLİNÇLİ NO-OP (bootstrap sıra düzeltmesi)
--
-- KÖK NEDEN (P2-9, 2026-10-02 nihai denetim): Bu dosya cupping_topics / cupping_points
--   üzerindeki composite UNIQUE(tenant_id, id) hedeflerine FK kuruyordu; o tablolar
--   20261216000000_cupping_schema.sql, UNIQUE'ler 20261217000000_cupping_content_foundation.sql
--   ile oluşur. Migration'lar dosya adı (zaman damgası) sırasıyla TEMİZ bir veritabanına
--   uygulandığında bu dosya 'relation "public.cupping_topics" does not exist' ile kırılıyordu.
--
-- ÇÖZÜM: İçerik (cupping_topic_notes + cupping_topic_note_points DDL'i) HİÇ DEĞİŞTİRİLMEDEN,
--   bağımlılıklardan SONRA çalışan 20261227000000_cupping_topic_note_atomic_update.sql
--   dosyasının başına ("BÖLÜM 0") taşındı. O blok tamamen idempotenttir
--   (CREATE TABLE IF NOT EXISTS / conname guard / INDEX IF NOT EXISTS / REVOKE / ENABLE RLS).
--
-- PRODUCTION / MEVCUT ORTAMLAR: Bu versiyon ve 20261227000000 zaten uygulanmıştır; hiçbiri
--   yeniden çalıştırılmaz → şema, veri ve migration geçmişi DEĞİŞMEZ. Yeni versiyon EKLENMEDİ
--   (geçmiş kaydı gerekmez). Temiz kurulumda bu dosya hiçbir şey yapmaz; tablolar 20261227'de
--   aynı tanımla oluşur → nihai şema birebir aynıdır.
-- =============================================================================

SELECT 1; -- no-op (bkz. yukarıdaki açıklama)
