-- ============================================================================
-- DEMO VİTRİN — Doğaltaş SENTETİK vitrin verisi (uzman@test.com demo tenant'ı)
--
-- OTOMATİK ÜRETİLDİ — elle düzenleme. Kaynak: lib/demo/demoDogaltasFixture.ts
-- Üretici: npx tsx scripts/demo-vitrin/buildDogaltasSeedSql.ts (harness --check ile doğrular).
--
-- NEDEN: d83ddd4a ile demo hesabın owner tenant'ındaki GERÇEK taşları okuması (cross-tenant
-- birleşim) güvenlik gereği kaldırıldı; GERİ GETİRİLMEZ. Vitrin bunun yerine demo tenant'ına ait
-- açıkça SENTETİK kayıtlarla doldurulur: 20 taş + 6 Taş Bilgi Kütüphanesi makalesi.
-- Owner kayıtlarından içerik / UUID / tenant / user referansı KOPYALANMAZ; görsel YOK (images=[]).
--
-- KAPSAM: YALNIZ demo tenant 40f842a0-e3e8-448c-8971-9a938e1faccb (users.is_demo_account=true, email=uzman@test.com).
-- İDEMPOTENT: sabit id'ler + ON CONFLICT (id) DO NOTHING → tekrar uygulama duplicate üretmez,
-- mevcut satırı DEĞİŞTİRMEZ (overwrite yok).
-- KİLİT: tenant yoksa, demo kullanıcı yoksa veya tenant'ta demo-OLMAYAN kullanıcı varsa HATA verir ve
-- hiçbir şey yazmaz (tek transaction). Sabit id'ler başka bir tenant'ta mevcutsa da DURUR.
-- NOT: stones / stone_knowledge_articles üzerindeki Yaşam Hafızası CDC tetikleyicileri outbox olayı
-- üretir; işçi demo tenant'ını "excluded-demo" ile kapatır (index'e demo verisi YAZILMAZ).
-- ============================================================================
BEGIN;

DO $demo_dogaltas_guard$
DECLARE
  v_demo_user uuid;
  v_non_demo integer;
  v_foreign integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.tenants WHERE id = '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid) THEN
    RAISE EXCEPTION 'demo dogaltas seed: demo tenant bulunamadı';
  END IF;
  SELECT count(*) INTO v_non_demo FROM public.users
   WHERE tenant_id = '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid AND coalesce(is_demo_account, false) = false;
  IF v_non_demo > 0 THEN
    RAISE EXCEPTION 'demo dogaltas seed: demo tenant demo-olmayan kullanıcı içeriyor (%) — durduruldu', v_non_demo;
  END IF;
  v_demo_user := (SELECT u.id FROM public.users u WHERE u.tenant_id = '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid
                    AND u.is_demo_account IS TRUE AND lower(btrim(u.email)) = 'uzman@test.com');
  IF v_demo_user IS NULL THEN
    RAISE EXCEPTION 'demo dogaltas seed: demo kullanıcı bulunamadı';
  END IF;
  SELECT (SELECT count(*) FROM public.stones WHERE id::text LIKE 'de5a0020-c11e-4000-8000-%' AND tenant_id IS DISTINCT FROM '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid)
       + (SELECT count(*) FROM public.stone_knowledge_articles WHERE id::text LIKE 'de5a0021-c11e-4000-8000-%' AND tenant_id IS DISTINCT FROM '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid)
    INTO v_foreign;
  IF v_foreign > 0 THEN
    RAISE EXCEPTION 'demo dogaltas seed: sabit id başka tenantta mevcut (%) — durduruldu', v_foreign;
  END IF;
END
$demo_dogaltas_guard$;

-- Sentetik taşlar (görsel yok)
INSERT INTO public.stones (id, tenant_id, stone_name, short_description, general_info, source_note, physical_effects, spiritual_effects, other_effects, warning_text, warning_tags, feng_shui, meditation, care, application, chakras, assignments, images, created_at, updated_at)
VALUES
  ('de5a0020-c11e-4000-8000-000000000001'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'AGAT', 'Agat; denge ve istikrar temasıyla ilişkilendirilen, katmanlı, bantlı; gri, kahve, mavi tonları renkli bir taştır. (Sentetik örnek kayıt)', 'Agat, Kalsedon (mikrokristalin kuvars) grubunda yer alır. Kimyasal formülü SiO₂, Mohs sertliği 6,5–7 olarak bilinir. Renk aralığı: katmanlı, bantlı; gri, kahve, mavi tonları. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında deri ve bağırsaklar bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kök Çakra ile eşleştirilir; denge ve istikrar niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Toprak. Mizaç eşleşmesi: Balgam. Burç geleneğinde İkizler, Başak ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında denge ve istikrar niyetini simgelemek için girişin yakını veya merkez bölümünde konumlandırılır.', 'Meditasyon sırasında kök çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Ilık su ve yumuşak bir bezle temizlenebilir; kuruladıktan sonra kumaş kese içinde saklanması önerilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır.', '["Kök Çakra"]'::jsonb, '{"Elementler":[["Toprak"]],"Mineraller":[["SİLİSYUM"],["OKSİJEN"],["DEMİR"]],"Etkili Organlar":[["Deri"],["Bağırsaklar"]],"Çakra Atama":[["Kök Çakra"]],"Burçlar":[["İkizler"],["Başak"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-7 minutes'), (now() + interval '-7 minutes')),
  ('de5a0020-c11e-4000-8000-000000000002'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'AKUAMARİN', 'Akuamarin; sakin iletişim ve ifade temasıyla ilişkilendirilen, açık mavi, deniz mavisi renkli bir taştır. (Sentetik örnek kayıt)', 'Akuamarin, Beril grubunda yer alır. Kimyasal formülü Be₃Al₂Si₆O₁₈, Mohs sertliği 7,5–8 olarak bilinir. Renk aralığı: açık mavi, deniz mavisi. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında boğaz ve akciğerler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Boğaz Çakrası ve Kalp Çakrası ile eşleştirilir; sakin iletişim ve ifade niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Su. Mizaç eşleşmesi: Balgam. Burç geleneğinde Balık, Kova ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında sakin iletişim ve ifade niyetini simgelemek için evin kuzey bölümünde konumlandırılır.', 'Meditasyon sırasında boğaz çakrası ve kalp çakrası bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Uzun süre doğrudan güneş ışığında rengi açılabilir; gölgede, kumaş kese içinde saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Boğaz Çakrası","Kalp Çakrası"]'::jsonb, '{"Elementler":[["Su"]],"Mineraller":[["BERİLYUM"],["ALÜMİNYUM"],["SİLİSYUM"],["DEMİR"]],"Etkili Organlar":[["Boğaz"],["Akciğerler"]],"Çakra Atama":[["Boğaz Çakrası"],["Kalp Çakrası"]],"Burçlar":[["Balık"],["Kova"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-14 minutes'), (now() + interval '-14 minutes')),
  ('de5a0020-c11e-4000-8000-000000000003'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'AMAZONİT', 'Amazonit; uyum ve sakinlik temasıyla ilişkilendirilen, yeşil-turkuaz renkli bir taştır. (Sentetik örnek kayıt)', 'Amazonit, Mikroklin feldispat grubunda yer alır. Kimyasal formülü KAlSi₃O₈, Mohs sertliği 6–6,5 olarak bilinir. Renk aralığı: yeşil-turkuaz. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kalp ve boğaz bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kalp Çakrası ve Boğaz Çakrası ile eşleştirilir; uyum ve sakinlik niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Su. Mizaç eşleşmesi: Balgam. Burç geleneğinde Başak ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Bileşiminde eser miktarda kurşun bulunabildiği için ağza alınmamalı ve iksir hazırlığında kullanılmamalıdır.', '["Genel Uyarı","Çocuklar"]'::jsonb, 'Feng shui uygulamalarında uyum ve sakinlik niyetini simgelemek için evin kuzey bölümünde konumlandırılır.', 'Meditasyon sırasında kalp çakrası ve boğaz çakrası bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kalp Çakrası","Boğaz Çakrası"]'::jsonb, '{"Elementler":[["Su"]],"Mineraller":[["POTASYUM"],["ALÜMİNYUM"],["SİLİSYUM"],["KURŞUN"]],"Etkili Organlar":[["Kalp"],["Boğaz"]],"Çakra Atama":[["Kalp Çakrası"],["Boğaz Çakrası"]],"Burçlar":[["Başak"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-21 minutes'), (now() + interval '-21 minutes')),
  ('de5a0020-c11e-4000-8000-000000000004'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'AMETİST', 'Ametist; sakinlik ve odak temasıyla ilişkilendirilen, lila, mor, menekşe renkli bir taştır. (Sentetik örnek kayıt)', 'Ametist, Kuvars grubunda yer alır. Kimyasal formülü SiO₂ (eser demir), Mohs sertliği 7 olarak bilinir. Renk aralığı: lila, mor, menekşe. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında sinir sistemi ve baş bölgesi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Taç Çakra ve Üçüncü Göz ile eşleştirilir; sakinlik ve odak niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Hava. Mizaç eşleşmesi: Sevda. Burç geleneğinde Balık, Kova, Yay ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Uyku / Huzursuzluk"]'::jsonb, 'Feng shui uygulamalarında sakinlik ve odak niyetini simgelemek için çalışma alanının doğu bölümünde konumlandırılır.', 'Meditasyon sırasında taç çakra ve üçüncü göz bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Uzun süre doğrudan güneş ışığında rengi açılabilir; gölgede, kumaş kese içinde saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Taç Çakra","Üçüncü Göz"]'::jsonb, '{"Elementler":[["Hava"]],"Mineraller":[["SİLİSYUM"],["OKSİJEN"],["DEMİR"],["MANGANEZ"]],"Etkili Organlar":[["Sinir sistemi"],["Baş bölgesi"]],"Çakra Atama":[["Taç Çakra"],["Üçüncü Göz"]],"Burçlar":[["Balık"],["Kova"],["Yay"]],"Mizaçlar":[["Sevda"]]}'::jsonb, '[]'::jsonb, (now() + interval '-28 minutes'), (now() + interval '-28 minutes')),
  ('de5a0020-c11e-4000-8000-000000000005'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'FLORİT', 'Florit; düzen ve zihinsel netlik temasıyla ilişkilendirilen, mor, yeşil, mavi; bantlı renkli bir taştır. (Sentetik örnek kayıt)', 'Florit, Halojenür grubunda yer alır. Kimyasal formülü CaF₂, Mohs sertliği 4 olarak bilinir. Renk aralığı: mor, yeşil, mavi; bantlı. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kemikler ve dişler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Üçüncü Göz ve Kalp Çakrası ile eşleştirilir; düzen ve zihinsel netlik niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Hava. Mizaç eşleşmesi: Balgam. Burç geleneğinde Oğlak, Balık ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Yumuşak ve kolay kırılan bir taştır; ağza alınmamalı, iksir hazırlığında kullanılmamalıdır.', '["Genel Uyarı","Çocuklar"]'::jsonb, 'Feng shui uygulamalarında düzen ve zihinsel netlik niyetini simgelemek için çalışma alanının doğu bölümünde konumlandırılır.', 'Meditasyon sırasında üçüncü göz ve kalp çakrası bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Suya ve doğrudan güneşe karşı hassastır; kuru temizlenmeli, gölgede ve tek başına saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Üçüncü Göz","Kalp Çakrası"]'::jsonb, '{"Elementler":[["Hava"]],"Mineraller":[["KALSİYUM"],["FLOR"]],"Etkili Organlar":[["Kemikler"],["Dişler"]],"Çakra Atama":[["Üçüncü Göz"],["Kalp Çakrası"]],"Burçlar":[["Oğlak"],["Balık"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-35 minutes'), (now() + interval '-35 minutes')),
  ('de5a0020-c11e-4000-8000-000000000006'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'GRANAT', 'Granat; canlılık ve kararlılık temasıyla ilişkilendirilen, koyu kırmızı, bordo renkli bir taştır. (Sentetik örnek kayıt)', 'Granat, Granat grubu (almandin) grubunda yer alır. Kimyasal formülü Fe₃Al₂(SiO₄)₃, Mohs sertliği 7–7,5 olarak bilinir. Renk aralığı: koyu kırmızı, bordo. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kan dolaşımı ve kalp bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kök Çakra ve Sakral Çakra ile eşleştirilir; canlılık ve kararlılık niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Safra. Burç geleneğinde Oğlak, Koç ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Tansiyon","Enerji Hassasiyeti"]'::jsonb, 'Feng shui uygulamalarında canlılık ve kararlılık niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında kök çakra ve sakral çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Ilık su ve yumuşak bir bezle temizlenebilir; kuruladıktan sonra kumaş kese içinde saklanması önerilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır.', '["Kök Çakra","Sakral Çakra"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["DEMİR"],["ALÜMİNYUM"],["SİLİSYUM"]],"Etkili Organlar":[["Kan dolaşımı"],["Kalp"]],"Çakra Atama":[["Kök Çakra"],["Sakral Çakra"]],"Burçlar":[["Oğlak"],["Koç"]],"Mizaçlar":[["Safra"]]}'::jsonb, '[]'::jsonb, (now() + interval '-42 minutes'), (now() + interval '-42 minutes')),
  ('de5a0020-c11e-4000-8000-000000000007'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'HEMATİT', 'Hematit; topraklanma ve koruma temasıyla ilişkilendirilen, metalik gri-siyah renkli bir taştır. (Sentetik örnek kayıt)', 'Hematit, Demir oksit grubunda yer alır. Kimyasal formülü Fe₂O₃, Mohs sertliği 5–6,5 olarak bilinir. Renk aralığı: metalik gri-siyah. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kan ve bacaklar bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kök Çakra ile eşleştirilir; topraklanma ve koruma niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Toprak. Mizaç eşleşmesi: Sevda. Burç geleneğinde Koç, Kova ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Tansiyon"]'::jsonb, 'Feng shui uygulamalarında topraklanma ve koruma niyetini simgelemek için girişin yakını veya merkez bölümünde konumlandırılır.', 'Meditasyon sırasında kök çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kök Çakra"]'::jsonb, '{"Elementler":[["Toprak"]],"Mineraller":[["DEMİR"],["OKSİJEN"]],"Etkili Organlar":[["Kan"],["Bacaklar"]],"Çakra Atama":[["Kök Çakra"]],"Burçlar":[["Koç"],["Kova"]],"Mizaçlar":[["Sevda"]]}'::jsonb, '[]'::jsonb, (now() + interval '-49 minutes'), (now() + interval '-49 minutes')),
  ('de5a0020-c11e-4000-8000-000000000008'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'KAPLAN GÖZÜ', 'Kaplan Gözü; özgüven ve odak temasıyla ilişkilendirilen, altın-kahve, ışık oyunlu renkli bir taştır. (Sentetik örnek kayıt)', 'Kaplan Gözü, Kuvars (lifli psödomorf) grubunda yer alır. Kimyasal formülü SiO₂ (demir oksitli), Mohs sertliği 7 olarak bilinir. Renk aralığı: altın-kahve, ışık oyunlu. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında mide ve sindirim sistemi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Solar Pleksus ve Sakral Çakra ile eşleştirilir; özgüven ve odak niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Safra. Burç geleneğinde Aslan, Oğlak ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında özgüven ve odak niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında solar pleksus ve sakral çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Ilık su ve yumuşak bir bezle temizlenebilir; kuruladıktan sonra kumaş kese içinde saklanması önerilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır.', '["Solar Pleksus","Sakral Çakra"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["SİLİSYUM"],["DEMİR"],["OKSİJEN"]],"Etkili Organlar":[["Mide"],["Sindirim sistemi"]],"Çakra Atama":[["Solar Pleksus"],["Sakral Çakra"]],"Burçlar":[["Aslan"],["Oğlak"]],"Mizaçlar":[["Safra"]]}'::jsonb, '[]'::jsonb, (now() + interval '-56 minutes'), (now() + interval '-56 minutes')),
  ('de5a0020-c11e-4000-8000-000000000009'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'KARNELYAN', 'Karnelyan; motivasyon ve yaratıcılık temasıyla ilişkilendirilen, turuncu, kırmızı-turuncu renkli bir taştır. (Sentetik örnek kayıt)', 'Karnelyan, Kalsedon grubunda yer alır. Kimyasal formülü SiO₂ (demir oksitli), Mohs sertliği 6,5–7 olarak bilinir. Renk aralığı: turuncu, kırmızı-turuncu. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında bel bölgesi ve böbrekler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Sakral Çakra ile eşleştirilir; motivasyon ve yaratıcılık niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Dem. Burç geleneğinde Koç, Aslan ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Tansiyon"]'::jsonb, 'Feng shui uygulamalarında motivasyon ve yaratıcılık niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında sakral çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Uzun süre doğrudan güneş ışığında rengi açılabilir; gölgede, kumaş kese içinde saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Sakral Çakra"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["SİLİSYUM"],["DEMİR"],["OKSİJEN"]],"Etkili Organlar":[["Bel bölgesi"],["Böbrekler"]],"Çakra Atama":[["Sakral Çakra"]],"Burçlar":[["Koç"],["Aslan"]],"Mizaçlar":[["Dem"]]}'::jsonb, '[]'::jsonb, (now() + interval '-63 minutes'), (now() + interval '-63 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000a'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'LABRADORİT', 'Labradorit; sezgi ve dönüşüm temasıyla ilişkilendirilen, gri zemin üzerinde mavi-yeşil yanardöner renkli bir taştır. (Sentetik örnek kayıt)', 'Labradorit, Plajiyoklaz feldispat grubunda yer alır. Kimyasal formülü (Ca,Na)(Al,Si)₄O₈, Mohs sertliği 6–6,5 olarak bilinir. Renk aralığı: gri zemin üzerinde mavi-yeşil yanardöner. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında gözler ve sinir sistemi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Üçüncü Göz ve Taç Çakra ile eşleştirilir; sezgi ve dönüşüm niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Su. Mizaç eşleşmesi: Sevda. Burç geleneğinde Yay, Akrep ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Psikolojik Hassasiyet"]'::jsonb, 'Feng shui uygulamalarında sezgi ve dönüşüm niyetini simgelemek için evin kuzey bölümünde konumlandırılır.', 'Meditasyon sırasında üçüncü göz ve taç çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Üçüncü Göz","Taç Çakra"]'::jsonb, '{"Elementler":[["Su"]],"Mineraller":[["KALSİYUM"],["SODYUM"],["ALÜMİNYUM"],["SİLİSYUM"]],"Etkili Organlar":[["Gözler"],["Sinir sistemi"]],"Çakra Atama":[["Üçüncü Göz"],["Taç Çakra"]],"Burçlar":[["Yay"],["Akrep"]],"Mizaçlar":[["Sevda"]]}'::jsonb, '[]'::jsonb, (now() + interval '-70 minutes'), (now() + interval '-70 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000b'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'LAPİSLAZULİ', 'Lapislazuli; bilgelik ve ifade temasıyla ilişkilendirilen, lacivert, altın renkli pirit noktalı renkli bir taştır. (Sentetik örnek kayıt)', 'Lapislazuli, Kaya (lazurit ağırlıklı) grubunda yer alır. Kimyasal formülü (Na,Ca)₈(AlSiO₄)₆(S,SO₄,Cl), Mohs sertliği 5–5,5 olarak bilinir. Renk aralığı: lacivert, altın renkli pirit noktalı. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında boğaz ve baş bölgesi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Üçüncü Göz ve Boğaz Çakrası ile eşleştirilir; bilgelik ve ifade niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Hava. Mizaç eşleşmesi: Balgam. Burç geleneğinde Yay, Terazi ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında bilgelik ve ifade niyetini simgelemek için çalışma alanının doğu bölümünde konumlandırılır.', 'Meditasyon sırasında üçüncü göz ve boğaz çakrası bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Üçüncü Göz","Boğaz Çakrası"]'::jsonb, '{"Elementler":[["Hava"]],"Mineraller":[["SODYUM"],["KALSİYUM"],["ALÜMİNYUM"],["SİLİSYUM"],["SÜLFÜR"]],"Etkili Organlar":[["Boğaz"],["Baş bölgesi"]],"Çakra Atama":[["Üçüncü Göz"],["Boğaz Çakrası"]],"Burçlar":[["Yay"],["Terazi"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-77 minutes'), (now() + interval '-77 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000c'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'LEPİDOLİT', 'Lepidolit; rahatlama ve dinginlik temasıyla ilişkilendirilen, pembe-lila, pullu renkli bir taştır. (Sentetik örnek kayıt)', 'Lepidolit, Mika grubunda yer alır. Kimyasal formülü K(Li,Al)₃(Al,Si)₄O₁₀(F,OH)₂, Mohs sertliği 2,5–3 olarak bilinir. Renk aralığı: pembe-lila, pullu. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında sinir sistemi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kalp Çakrası ve Taç Çakra ile eşleştirilir; rahatlama ve dinginlik niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Su. Mizaç eşleşmesi: Balgam. Burç geleneğinde Terazi ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Lityum içerir; ağza alınmamalı ve iksir hazırlığında kullanılmamalıdır.', '["Uzman Kontrolü","Çocuklar"]'::jsonb, 'Feng shui uygulamalarında rahatlama ve dinginlik niyetini simgelemek için evin kuzey bölümünde konumlandırılır.', 'Meditasyon sırasında kalp çakrası ve taç çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kalp Çakrası","Taç Çakra"]'::jsonb, '{"Elementler":[["Su"]],"Mineraller":[["LİTYUM"],["POTASYUM"],["ALÜMİNYUM"],["FLOR"]],"Etkili Organlar":[["Sinir sistemi"]],"Çakra Atama":[["Kalp Çakrası"],["Taç Çakra"]],"Burçlar":[["Terazi"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-84 minutes'), (now() + interval '-84 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000d'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'MALAHİT', 'Malahit; dönüşüm ve cesaret temasıyla ilişkilendirilen, koyu ve açık yeşil bantlı renkli bir taştır. (Sentetik örnek kayıt)', 'Malahit, Bakır karbonat grubunda yer alır. Kimyasal formülü Cu₂CO₃(OH)₂, Mohs sertliği 3,5–4 olarak bilinir. Renk aralığı: koyu ve açık yeşil bantlı. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında karaciğer ve eklemler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kalp Çakrası ve Solar Pleksus ile eşleştirilir; dönüşüm ve cesaret niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Toprak. Mizaç eşleşmesi: Safra. Burç geleneğinde Akrep, Oğlak ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Bakır içerir; tozu solunmamalı, işlenmemiş hâli cilde uzun süre temas ettirilmemeli ve iksirde kullanılmamalıdır.', '["Hamilelik","Çocuklar","Alerji"]'::jsonb, 'Feng shui uygulamalarında dönüşüm ve cesaret niyetini simgelemek için girişin yakını veya merkez bölümünde konumlandırılır.', 'Meditasyon sırasında kalp çakrası ve solar pleksus bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kalp Çakrası","Solar Pleksus"]'::jsonb, '{"Elementler":[["Toprak"]],"Mineraller":[["BAKIR"],["OKSİJEN"]],"Etkili Organlar":[["Karaciğer"],["Eklemler"]],"Çakra Atama":[["Kalp Çakrası"],["Solar Pleksus"]],"Burçlar":[["Akrep"],["Oğlak"]],"Mizaçlar":[["Safra"]]}'::jsonb, '[]'::jsonb, (now() + interval '-91 minutes'), (now() + interval '-91 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000e'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'OBSİDYEN (SİYAH)', 'Obsidyen (Siyah); koruma ve farkındalık temasıyla ilişkilendirilen, parlak siyah renkli bir taştır. (Sentetik örnek kayıt)', 'Obsidyen (Siyah), Volkanik cam grubunda yer alır. Kimyasal formülü SiO₂ ağırlıklı amorf, Mohs sertliği 5–5,5 olarak bilinir. Renk aralığı: parlak siyah. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında bacaklar ve bağırsaklar bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kök Çakra ile eşleştirilir; koruma ve farkındalık niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Toprak. Mizaç eşleşmesi: Sevda. Burç geleneğinde Akrep, Yay ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Psikolojik Hassasiyet","Enerji Hassasiyeti"]'::jsonb, 'Feng shui uygulamalarında koruma ve farkındalık niyetini simgelemek için girişin yakını veya merkez bölümünde konumlandırılır.', 'Meditasyon sırasında kök çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Ilık su ve yumuşak bir bezle temizlenebilir; kuruladıktan sonra kumaş kese içinde saklanması önerilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır.', '["Kök Çakra"]'::jsonb, '{"Elementler":[["Toprak"]],"Mineraller":[["SİLİSYUM"],["OKSİJEN"],["DEMİR"],["MAGNEZYUM"]],"Etkili Organlar":[["Bacaklar"],["Bağırsaklar"]],"Çakra Atama":[["Kök Çakra"]],"Burçlar":[["Akrep"],["Yay"]],"Mizaçlar":[["Sevda"]]}'::jsonb, '[]'::jsonb, (now() + interval '-98 minutes'), (now() + interval '-98 minutes')),
  ('de5a0020-c11e-4000-8000-00000000000f'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'PEMBE KUVARS', 'Pembe Kuvars; şefkat ve iç huzur temasıyla ilişkilendirilen, açık pembe, süt pembesi renkli bir taştır. (Sentetik örnek kayıt)', 'Pembe Kuvars, Kuvars grubunda yer alır. Kimyasal formülü SiO₂ (eser titan/mangan), Mohs sertliği 7 olarak bilinir. Renk aralığı: açık pembe, süt pembesi. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kalp ve deri bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kalp Çakrası ile eşleştirilir; şefkat ve iç huzur niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Su. Mizaç eşleşmesi: Dem. Burç geleneğinde Boğa, Terazi ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında şefkat ve iç huzur niyetini simgelemek için evin kuzey bölümünde konumlandırılır.', 'Meditasyon sırasında kalp çakrası bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Uzun süre doğrudan güneş ışığında rengi açılabilir; gölgede, kumaş kese içinde saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kalp Çakrası"]'::jsonb, '{"Elementler":[["Su"]],"Mineraller":[["SİLİSYUM"],["OKSİJEN"],["TİTAN"],["MANGANEZ"]],"Etkili Organlar":[["Kalp"],["Deri"]],"Çakra Atama":[["Kalp Çakrası"]],"Burçlar":[["Boğa"],["Terazi"]],"Mizaçlar":[["Dem"]]}'::jsonb, '[]'::jsonb, (now() + interval '-105 minutes'), (now() + interval '-105 minutes')),
  ('de5a0020-c11e-4000-8000-000000000010'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'PİRİT', 'Pirit; irade ve bolluk niyeti temasıyla ilişkilendirilen, metalik pirinç sarısı renkli bir taştır. (Sentetik örnek kayıt)', 'Pirit, Demir sülfür grubunda yer alır. Kimyasal formülü FeS₂, Mohs sertliği 6–6,5 olarak bilinir. Renk aralığı: metalik pirinç sarısı. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında mide ve akciğerler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Solar Pleksus ile eşleştirilir; irade ve bolluk niyeti niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Safra. Burç geleneğinde Aslan ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Nemli ortamda oksitlenebilir; ağza alınmamalı ve iksir hazırlığında kullanılmamalıdır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında irade ve bolluk niyeti niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında solar pleksus bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Solar Pleksus"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["DEMİR"],["SÜLFÜR"]],"Etkili Organlar":[["Mide"],["Akciğerler"]],"Çakra Atama":[["Solar Pleksus"]],"Burçlar":[["Aslan"]],"Mizaçlar":[["Safra"]]}'::jsonb, '[]'::jsonb, (now() + interval '-112 minutes'), (now() + interval '-112 minutes')),
  ('de5a0020-c11e-4000-8000-000000000011'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'RODOKROZİT', 'Rodokrozit; duygusal yenilenme temasıyla ilişkilendirilen, pembe-kırmızı bantlı renkli bir taştır. (Sentetik örnek kayıt)', 'Rodokrozit, Manganez karbonat grubunda yer alır. Kimyasal formülü MnCO₃, Mohs sertliği 3,5–4 olarak bilinir. Renk aralığı: pembe-kırmızı bantlı. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında kalp ve böbrekler bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kalp Çakrası ve Solar Pleksus ile eşleştirilir; duygusal yenilenme niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Dem. Burç geleneğinde Akrep, Aslan ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında duygusal yenilenme niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında kalp çakrası ve solar pleksus bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Suya ve doğrudan güneşe karşı hassastır; kuru temizlenmeli, gölgede ve tek başına saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Kalp Çakrası","Solar Pleksus"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["MANGANEZ"],["OKSİJEN"]],"Etkili Organlar":[["Kalp"],["Böbrekler"]],"Çakra Atama":[["Kalp Çakrası"],["Solar Pleksus"]],"Burçlar":[["Akrep"],["Aslan"]],"Mizaçlar":[["Dem"]]}'::jsonb, '[]'::jsonb, (now() + interval '-119 minutes'), (now() + interval '-119 minutes')),
  ('de5a0020-c11e-4000-8000-000000000012'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'SELENİT', 'Selenit; arınma ve hafiflik temasıyla ilişkilendirilen, beyaz, ipeksi parlak renkli bir taştır. (Sentetik örnek kayıt)', 'Selenit, Alçıtaşı (jips) grubunda yer alır. Kimyasal formülü CaSO₄·2H₂O, Mohs sertliği 2 olarak bilinir. Renk aralığı: beyaz, ipeksi parlak. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında omurga ve sinir sistemi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Taç Çakra ile eşleştirilir; arınma ve hafiflik niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Hava. Mizaç eşleşmesi: Balgam. Burç geleneğinde Yengeç, Boğa ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır. Suda çözünür; suyla temizlenmemeli ve nemli ortamda saklanmamalıdır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında arınma ve hafiflik niyetini simgelemek için çalışma alanının doğu bölümünde konumlandırılır.', 'Meditasyon sırasında taç çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Su ile temizlenmesi önerilmez; kuru, yumuşak bir fırça veya tütsü/ses ile enerjisel temizlik tercih edilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Taç Çakra"]'::jsonb, '{"Elementler":[["Hava"]],"Mineraller":[["KALSİYUM"],["SÜLFÜR"],["OKSİJEN"]],"Etkili Organlar":[["Omurga"],["Sinir sistemi"]],"Çakra Atama":[["Taç Çakra"]],"Burçlar":[["Yengeç"],["Boğa"]],"Mizaçlar":[["Balgam"]]}'::jsonb, '[]'::jsonb, (now() + interval '-126 minutes'), (now() + interval '-126 minutes')),
  ('de5a0020-c11e-4000-8000-000000000013'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'SİTRİN', 'Sitrin; neşe ve canlılık temasıyla ilişkilendirilen, açık sarı, bal rengi renkli bir taştır. (Sentetik örnek kayıt)', 'Sitrin, Kuvars grubunda yer alır. Kimyasal formülü SiO₂ (eser demir), Mohs sertliği 7 olarak bilinir. Renk aralığı: açık sarı, bal rengi. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında mide ve sindirim sistemi bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Solar Pleksus ve Sakral Çakra ile eşleştirilir; neşe ve canlılık niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Ateş. Mizaç eşleşmesi: Safra. Burç geleneğinde Aslan, İkizler, Koç ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Enerji Hassasiyeti"]'::jsonb, 'Feng shui uygulamalarında neşe ve canlılık niyetini simgelemek için evin güney bölümünde konumlandırılır.', 'Meditasyon sırasında solar pleksus ve sakral çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Uzun süre doğrudan güneş ışığında rengi açılabilir; gölgede, kumaş kese içinde saklanmalıdır.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır. İksir (su) hazırlığında kullanılmaz.', '["Solar Pleksus","Sakral Çakra"]'::jsonb, '{"Elementler":[["Ateş"]],"Mineraller":[["SİLİSYUM"],["OKSİJEN"],["DEMİR"]],"Etkili Organlar":[["Mide"],["Sindirim sistemi"]],"Çakra Atama":[["Solar Pleksus"],["Sakral Çakra"]],"Burçlar":[["Aslan"],["İkizler"],["Koç"]],"Mizaçlar":[["Safra"]]}'::jsonb, '[]'::jsonb, (now() + interval '-133 minutes'), (now() + interval '-133 minutes')),
  ('de5a0020-c11e-4000-8000-000000000014'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'TURMALİN (SİYAH)', 'Turmalin (Siyah); koruma ve topraklanma temasıyla ilişkilendirilen, siyah, çizgili prizmatik renkli bir taştır. (Sentetik örnek kayıt)', 'Turmalin (Siyah), Turmalin grubu (şörl) grubunda yer alır. Kimyasal formülü NaFe₃Al₆(BO₃)₃Si₆O₁₈(OH)₄, Mohs sertliği 7–7,5 olarak bilinir. Renk aralığı: siyah, çizgili prizmatik. Bu kayıt Yaşam Sistemi vitrin hesabı için hazırlanmış örnek bir kayıttır.', 'Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek kayıttır. Geleneksel kullanım bilgisi niteliğindedir; tıbbi teşhis veya tedavinin yerine geçmez.', 'Geleneksel kristal çalışmalarında bacaklar ve bağışıklık bölgesiyle ilişkilendirilir. Bu bilgi tıbbi bir iddia değildir; sağlık sorunlarında hekime başvurulmalıdır.', 'Kök Çakra ile eşleştirilir; koruma ve topraklanma niyetiyle yapılan çalışmalarda destekleyici bir sembol olarak kullanılır.', 'Element: Toprak. Mizaç eşleşmesi: Sevda. Burç geleneğinde Oğlak, Akrep ile anılır.', 'Doğaltaşlar tıbbi tedavinin yerine geçmez; mevcut bir tedavi varsa uzman/hekim önerisi esastır.', '["Genel Uyarı"]'::jsonb, 'Feng shui uygulamalarında koruma ve topraklanma niyetini simgelemek için girişin yakını veya merkez bölümünde konumlandırılır.', 'Meditasyon sırasında kök çakra bölgesinin yakınında tutulabilir; 5–10 dakikalık sakin nefes çalışmasıyla birlikte kullanılır.', 'Ilık su ve yumuşak bir bezle temizlenebilir; kuruladıktan sonra kumaş kese içinde saklanması önerilir.', 'Cepte taşıma, masa üstünde bulundurma veya meditasyon sırasında elde tutma şeklinde kullanılır.', '["Kök Çakra"]'::jsonb, '{"Elementler":[["Toprak"]],"Mineraller":[["BOR"],["SODYUM"],["DEMİR"],["ALÜMİNYUM"],["SİLİSYUM"]],"Etkili Organlar":[["Bacaklar"],["Bağışıklık"]],"Çakra Atama":[["Kök Çakra"]],"Burçlar":[["Oğlak"],["Akrep"]],"Mizaçlar":[["Sevda"]]}'::jsonb, '[]'::jsonb, (now() + interval '-140 minutes'), (now() + interval '-140 minutes'))
ON CONFLICT (id) DO NOTHING;

-- Sentetik Taş Bilgi Kütüphanesi makaleleri
INSERT INTO public.stone_knowledge_articles (id, tenant_id, title, content, category, sub_category, tags, related_stones, related_minerals, source, keyword, is_active)
VALUES
  ('de5a0021-c11e-4000-8000-000000000001'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Mohs Sertlik Ölçeği ve Taşların Dayanıklılığı', 'Mohs ölçeği, minerallerin birbirini çizebilme özelliğine göre 1 ile 10 arasında sıralandığı göreceli bir sertlik ölçeğidir.

Selenit (2) tırnakla çizilebilecek kadar yumuşakken kuvars ailesindeki ametist ve sitrin (7) günlük kullanıma oldukça dayanıklıdır. Florit (4) gibi orta sertlikteki taşlar darbelere karşı korunmalıdır.

Uygulamada sertlik; taşın cepte taşınabilirliğini, birlikte saklanabileceği taşları ve temizlik yöntemini belirlemede ilk bakılacak bilgidir.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Mineroloji', 'Temel Bilgiler', ARRAY['mohs', 'sertlik', 'dayanıklılık']::text[], ARRAY['AMETİST', 'SELENİT', 'FLORİT']::text[], ARRAY['SİLİSYUM', 'KALSİYUM']::text[], 'Vitrin örnek içeriği', 'mohs sertlik', true),
  ('de5a0021-c11e-4000-8000-000000000002'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Doğaltaşların Temizlenmesi ve Saklanması', 'Her taş aynı yöntemle temizlenmez. Selenit suda çözünür; malahit ve pirit nemden etkilenir. Bu taşlar kuru bir fırça veya yumuşak bezle temizlenmelidir.

Ametist, sitrin ve pembe kuvars gibi renkli kuvarslar uzun süre doğrudan güneşte kaldığında solabilir. Taşları ayrı keselerde saklamak, sert taşların yumuşakları çizmesini önler.

Temizlik sonrasında taşın kayıt kartındaki ''Bakım'' alanına uygulanan yöntemi not etmek, danışan çalışmalarında tutarlılık sağlar.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Uygulamalar', 'Bakım', ARRAY['bakım', 'temizlik', 'saklama']::text[], ARRAY['SELENİT', 'MALAHİT', 'PİRİT', 'AMETİST']::text[], ARRAY['BAKIR', 'DEMİR']::text[], 'Vitrin örnek içeriği', 'taş bakımı', true),
  ('de5a0021-c11e-4000-8000-000000000003'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Çakra Renkleri ve Taş Eşleştirme Geleneği', 'Geleneksel uygulamalarda her çakra bir renk ile ilişkilendirilir ve taşlar çoğunlukla bu renk uyumuna göre seçilir: Kök çakra için siyah ve kırmızı taşlar, sakral çakra için turuncu, solar pleksus için sarı, kalp çakrası için pembe ve yeşil, boğaz çakrası için açık mavi, üçüncü göz için lacivert ve taç çakra için mor/beyaz tonlar.

Bu eşleştirme sembolik bir çerçevedir; uzmanlar danışanın ihtiyacına göre farklı tercihler yapabilir.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Şifa', 'Çakra Eşleştirme', ARRAY['çakra', 'renk', 'eşleştirme']::text[], ARRAY['TURMALİN (SİYAH)', 'KARNELYAN', 'SİTRİN', 'PEMBE KUVARS', 'AKUAMARİN', 'LAPİSLAZULİ', 'AMETİST']::text[], '{}'::text[], 'Vitrin örnek içeriği', 'çakra taşları', true),
  ('de5a0021-c11e-4000-8000-000000000004'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Kristal Çalışmalarına Bilimsel Bir Bakış', 'Doğaltaşların fiziksel sağlık üzerindeki etkilerine dair güçlü klinik kanıt bulunmamaktadır. Bu nedenle profesyonel uygulamada taşlar; rahatlama, odak ve niyet çalışmalarına eşlik eden tamamlayıcı semboller olarak konumlandırılmalıdır.

Etik uygulama için: danışana tıbbi vaatte bulunulmamalı, devam eden tedaviler değiştirilmemeli ve gerekli durumlarda hekime yönlendirme yapılmalıdır. Yaşam Sistemi''ndeki uyarı alanları bu yaklaşımı desteklemek için tasarlanmıştır.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Araştırma', 'Bilimsel Bakış', ARRAY['araştırma', 'kanıt', 'etik']::text[], '{}'::text[], '{}'::text[], 'Vitrin örnek içeriği', 'bilimsel bakış', true),
  ('de5a0021-c11e-4000-8000-000000000005'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Kuvars Ailesi: Ametist, Sitrin ve Pembe Kuvars', 'Kuvars, silisyum ve oksijenden (SiO₂) oluşan, yer kabuğunun en yaygın minerallerinden biridir. Renk farklılıkları çoğunlukla eser elementlerden kaynaklanır: Ametistin morluğu ve sitrinin sarılığı eser demirle, pembe kuvarsın rengi ise titan ve mangan gibi eserlerle ilişkilendirilir.

Kaplan gözü de lifli yapısıyla kuvars ailesinin ışık oyunlu bir üyesidir. Aynı aileden taşlar benzer sertlik (7) ve bakım ihtiyaçlarına sahiptir.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Mineroloji', 'Mineral Aileleri', ARRAY['kuvars', 'silisyum', 'renk']::text[], ARRAY['AMETİST', 'SİTRİN', 'PEMBE KUVARS', 'KAPLAN GÖZÜ']::text[], ARRAY['SİLİSYUM', 'OKSİJEN', 'DEMİR', 'TİTAN', 'MANGANEZ']::text[], 'Vitrin örnek içeriği', 'kuvars', true),
  ('de5a0021-c11e-4000-8000-000000000006'::uuid, '40f842a0-e3e8-448c-8971-9a938e1faccb'::uuid, 'Taş Kartlarını Danışan Çalışmasında Kullanmak', 'Doğaltaş listesindeki her kayıt; genel bilgi, çakra ve element atamaları, mineraller, uyarılar ve bakım notlarını tek kartta toplar.

Uzman, danışan detayındaki ''Taşlar'' sekmesinden önerdiği taşı kaydederken bu kartlardaki uyarı etiketlerini kontrol ederek güvenli bir öneri hazırlayabilir. Kombinasyon oluşturma ekranı ise mineral ihtiyaçlarına göre taş seçimine yardımcı olur.

Not: Bu makale Yaşam Sistemi vitrin hesabı için hazırlanmış SENTETİK örnek içeriktir; tıbbi tavsiye değildir.', 'Genel', 'Kullanım', ARRAY['kullanım', 'danışan', 'kayıt']::text[], ARRAY['AMETİST', 'HEMATİT']::text[], '{}'::text[], 'Vitrin örnek içeriği', 'taş kartı', true)
ON CONFLICT (id) DO NOTHING;

COMMIT;
